import { defineModule } from 'ketjs'
import { functions } from './functions.ts'
import { models } from './models.ts'
import { sections } from './sections.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'website_form',
  version: '0.1.0',
  app: true,
  install: 'auto',
  depends: ['website'],
  title: 'Biểu mẫu website',
  summary: 'Biểu mẫu có cấu trúc, chống spam và lưu submission theo từng website.',
  category: 'Website',
  messages: {
    vi: {
      'app.title': 'Biểu mẫu website',
      'app.summary': 'Biểu mẫu có cấu trúc, chống spam và lưu submission theo từng website.',
      'app.category': 'Website',
      'section.form': 'Biểu mẫu',
      'error.fieldsRequired': 'Biểu mẫu cần ít nhất một trường.',
      'error.invalidSchema': 'Cấu trúc schema biểu mẫu không hợp lệ.',
      'error.schemaTooLarge': 'Schema biểu mẫu vượt quá giới hạn cho phép.',
      'error.invalidFieldName': 'Tên trường không hợp lệ.',
      'error.duplicateField': 'Tên trường bị trùng.',
      'error.invalidFieldType': 'Loại trường không được hỗ trợ.',
      'error.payloadTooLarge': 'Dữ liệu gửi lên vượt quá giới hạn.',
      'error.unknownField': 'Trường không có trong schema.',
      'error.required': 'Thông tin bắt buộc.',
      'error.invalidEmail': 'Địa chỉ email không hợp lệ.',
      'error.invalidNumber': 'Giá trị số không hợp lệ.',
      'error.invalidCheckbox': 'Giá trị checkbox không hợp lệ.',
      'error.valueTooLong': 'Giá trị quá dài.',
      'error.siteNotFound': 'Không tìm thấy website.',
      'error.invalidName': 'Tên biểu mẫu không hợp lệ hoặc quá dài.',
      'error.duplicateName': 'Tên biểu mẫu đã được sử dụng trên website.',
      'error.invalidMessage': 'Thông báo thành công không hợp lệ hoặc quá dài.',
      'error.unavailable': 'Biểu mẫu hiện không khả dụng.',
      'error.rateLimit': 'Bạn đã gửi quá nhiều lần. Vui lòng thử lại sau.',
    },
    en: {
      'app.title': 'Website forms',
      'app.summary': 'Structured forms with spam protection and per-site submissions.',
      'app.category': 'Website',
      'section.form': 'Form',
      'error.fieldsRequired': 'A form needs at least one field.',
      'error.invalidSchema': 'The form schema structure is invalid.',
      'error.schemaTooLarge': 'The form schema exceeds the allowed size.',
      'error.invalidFieldName': 'The field name is invalid.',
      'error.duplicateField': 'The field name is duplicated.',
      'error.invalidFieldType': 'The field type is not supported.',
      'error.payloadTooLarge': 'The submitted payload exceeds the allowed size.',
      'error.unknownField': 'The field is not declared in the schema.',
      'error.required': 'This field is required.',
      'error.invalidEmail': 'The email address is invalid.',
      'error.invalidNumber': 'The numeric value is invalid.',
      'error.invalidCheckbox': 'The checkbox value is invalid.',
      'error.valueTooLong': 'The value is too long.',
      'error.siteNotFound': 'The site was not found.',
      'error.invalidName': 'The form name is invalid or too long.',
      'error.duplicateName': 'The form name is already in use on this site.',
      'error.invalidMessage': 'The success message is invalid or too long.',
      'error.unavailable': 'The form is not available.',
      'error.rateLimit': 'Too many submissions. Please try again later.',
    },
  },
  models,
  functions,
  sections,
  routes,
})
