import { defineModule } from 'ketjs'
import { islands } from './islands.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'stock_backend',
  version: '0.1.0',
  depends: ['stock', 'backend'],
  install: 'auto',
  app: true,
  assets: new URL('./client/', import.meta.url),
  islands,
  title: 'Kho trong quản trị',
  summary: 'Warehouse, tồn kho, dịch chuyển và routes.',
  category: 'Hệ thống',
  routes,
  joints: {
    'picking.collaboration': {
      props: { resModel: 'text', resId: 'id', lang: 'text' },
      multiple: true,
    },
    'picking.editor': { props: { pickingId: 'id', lang: 'text?' } },
  },
  menus: {
    stock: { label: 'menu.app', icon: 'warehouse', sequence: 30 },
    'stock.operations': { parent: 'stock', label: 'menu.operations', sequence: 10 },
    'stock.transfers': {
      parent: 'stock.operations',
      label: 'menu.transfers',
      path: '/admin/transfers',
      needs: 'stock.listPickings',
    },
    'stock.inventory': {
      parent: 'stock.operations',
      label: 'menu.inventory',
      path: '/admin/inventory',
      needs: 'stock.listQuants',
    },
    'stock.forecast': {
      parent: 'stock.operations',
      label: 'menu.forecast',
      path: '/admin/forecast',
      needs: 'stock.forecast',
    },
    'stock.replenishment': {
      parent: 'stock.operations',
      label: 'menu.replenishment',
      path: '/admin/replenishment',
      needs: 'stock.listOrderpoints',
    },
    'stock.config': { parent: 'stock', label: 'menu.config', sequence: 20 },
    'stock.warehouses': {
      parent: 'stock.config',
      label: 'menu.warehouses',
      path: '/admin/warehouses',
      needs: 'stock.listWarehouses',
    },
    'stock.locations': {
      parent: 'stock.config',
      label: 'menu.locations',
      path: '/admin/locations',
      needs: 'stock.listLocations',
    },
    'stock.pickingTypes': {
      parent: 'stock.config',
      label: 'menu.pickingTypes',
      path: '/admin/picking-types',
      needs: 'stock.listPickingTypes',
    },
    'stock.lots': {
      parent: 'stock.config',
      label: 'menu.lots',
      path: '/admin/lots',
      needs: 'stock.listLots',
    },
    'stock.routes': {
      parent: 'stock.config',
      label: 'menu.routes',
      path: '/admin/stock-routes',
      needs: 'stock.listRoutes',
    },
  },
  messages: {
    vi: {
      'app.title': 'Kho trong quản trị',
      'app.summary': 'Quản lý đa kho, tồn kho, dịch chuyển và quy tắc cung ứng.',
      'app.category': 'Hệ thống',
      'menu.app': 'Kho',
      'menu.operations': 'Vận hành',
      'menu.transfers': 'Dịch chuyển',
      'menu.inventory': 'Tồn kho',
      'menu.forecast': 'Dự báo',
      'menu.replenishment': 'Bổ sung hàng',
      'menu.config': 'Cấu hình',
      'menu.warehouses': 'Kho hàng',
      'menu.locations': 'Vị trí',
      'menu.pickingTypes': 'Loại hoạt động',
      'menu.lots': 'Lô / Sê-ri',
      'menu.routes': 'Tuyến cung ứng',
      inventory: 'Tồn kho',
      transfers: 'Dịch chuyển',
      warehouses: 'Kho hàng',
      routes: 'Tuyến cung ứng',
      locations: 'Vị trí kho',
      pickingTypes: 'Loại hoạt động',
      lots: 'Lô / Sê-ri',
      replenishment: 'Bổ sung hàng',
      forecast: 'Dự báo tồn kho',
      transferDetail: 'Chi tiết dịch chuyển',
      'transfer.kicker': 'Dịch chuyển kho',
      'transfer.collaboration.label': 'Trao đổi và hoạt động của dịch chuyển',
      'transfer.actions.label': 'Hành động dịch chuyển',
      'transfer.summary.lines': 'Dòng thao tác',
      'transfer.operations.title': 'Dòng dịch chuyển',
      'transfer.operations.hint': 'Theo dõi nhu cầu, số lượng đã xử lý và trạng thái từng dòng.',
      'transfer.operations.empty': 'Chưa có dòng dịch chuyển',
      'transfer.operations.emptyHint': 'Thêm sản phẩm vào dịch chuyển để bắt đầu xử lý.',
      'transfer.addMove.title': 'Thêm sản phẩm',
      'transfer.addMove.hint': 'Khai báo sản phẩm, đơn vị và số lượng cần dịch chuyển.',
      'transfer.recordDone.title': 'Ghi nhận xử lý',
      'transfer.recordDone.hint': 'Nhập số lượng thực tế và lô hoặc sê-ri khi cần.',
      routeDetail: 'Quy tắc tuyến cung ứng',
      'col.name': 'Tên',
      'col.kind': 'Loại',
      'col.state': 'Trạng thái',
      'col.detail': 'Chi tiết',
      empty: 'Chưa có dữ liệu.',
      emptyHint: 'Tạo bản ghi đầu tiên để bắt đầu.',
      'error.invalid': 'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại.',
      'action.create': 'Tạo mới',
      'action.apply': 'Áp dụng kiểm kê',
      'action.addMove': 'Thêm dòng hàng',
      'action.confirm': 'Xác nhận',
      'action.assign': 'Giữ hàng',
      'action.validate': 'Hoàn tất',
      'action.validateCreateBackorder': 'Hoàn tất và tạo đơn bù',
      'action.validateNoBackorder': 'Hoàn tất, không tạo đơn bù',
      'action.recordDone': 'Ghi nhận đã xử lý',
      'action.cancel': 'Hủy',
      'action.addRule': 'Thêm quy tắc',
      'action.calculate': 'Tính dự báo',
      'action.run': 'Chạy bổ sung',
      'adjustment.title': 'Điều chỉnh tồn kho',
      'field.productId': 'ID biến thể',
      'field.location': 'Vị trí',
      'field.inventoryLocation': 'Vị trí kiểm kê',
      'field.uom': 'Đơn vị tính',
      'field.lot': 'Lô / Sê-ri',
      'field.counted': 'Số lượng đếm được',
      'field.reference': 'Tham chiếu',
      'field.operationType': 'Loại hoạt động',
      'field.scheduledDate': 'Ngày dự kiến',
      'field.demand': 'Nhu cầu',
      'field.operationLine': 'Dòng xử lý',
      'field.doneQuantity': 'Số lượng đã xử lý',
      'field.code': 'Mã',
      'field.receptionSteps': 'Các bước nhận hàng',
      'field.deliverySteps': 'Các bước giao hàng',
      'field.usage': 'Cách sử dụng',
      'field.warehouse': 'Kho hàng',
      'field.parentLocation': 'Vị trí cha',
      'field.sourceLocation': 'Vị trí nguồn',
      'field.destinationLocation': 'Vị trí đích',
      'field.backorder': 'Tạo backorder',
      'field.lotSerial': 'Số lô / sê-ri',
      'field.note': 'Ghi chú',
      'field.sequence': 'Thứ tự',
      'field.ruleAction': 'Hành động',
      'field.procureMethod': 'Phương thức cung ứng',
      'field.trigger': 'Kích hoạt',
      'field.minQuantity': 'Tồn tối thiểu',
      'field.maxQuantity': 'Tồn tối đa',
      'field.replenishmentUom': 'Đơn vị bổ sung',
      'field.route': 'Tuyến cung ứng',
      'forecast.onHand': 'Tồn thực tế',
      'forecast.incoming': 'Sắp nhận',
      'forecast.outgoing': 'Sắp xuất',
      'forecast.value': 'Dự báo',
      'state.draft': 'Nháp',
      'state.waiting': 'Đang chờ',
      'state.confirmed': 'Đã xác nhận',
      'state.partially_available': 'Có hàng một phần',
      'state.reserved': 'Đã giữ hàng',
      'state.assigned': 'Đã giữ hàng',
      'state.done': 'Hoàn tất',
      'state.cancel': 'Đã hủy',
      'kind.quant': 'Tồn theo vị trí',
      'kind.transfer': 'Dịch chuyển',
      'kind.move': 'Dòng dịch chuyển',
      'kind.move-line': 'Dòng thao tác',
      'kind.warehouse': 'Kho hàng',
      'kind.lot': 'Lô / Sê-ri',
      'kind.route': 'Tuyến cung ứng',
      'kind.internal': 'Nội bộ',
      'kind.view': 'Nhóm vị trí',
      'kind.supplier': 'Nhà cung cấp',
      'kind.customer': 'Khách hàng',
      'kind.inventory': 'Kiểm kê',
      'kind.production': 'Sản xuất',
      'kind.transit': 'Trung chuyển',
      'kind.incoming': 'Nhập kho',
      'kind.outgoing': 'Xuất kho',
      'kind.pull': 'Kéo hàng',
      'kind.push': 'Đẩy hàng',
      'kind.pull_push': 'Kéo và đẩy hàng',
      'kind.auto': 'Tự động',
      'kind.manual': 'Thủ công',
      'receptionSteps.one_step': 'Nhận hàng trực tiếp',
      'receptionSteps.two_steps': 'Nhập qua khu vực đầu vào',
      'receptionSteps.three_steps': 'Đầu vào, kiểm tra chất lượng, nhập kho',
      'deliverySteps.ship_only': 'Giao trực tiếp',
      'deliverySteps.pick_ship': 'Lấy hàng rồi giao',
      'deliverySteps.pick_pack_ship': 'Lấy hàng, đóng gói rồi giao',
      'usage.internal': 'Vị trí nội bộ',
      'usage.view': 'Nhóm vị trí',
      'usage.supplier': 'Vị trí nhà cung cấp',
      'usage.customer': 'Vị trí khách hàng',
      'usage.inventory': 'Vị trí kiểm kê',
      'usage.production': 'Vị trí sản xuất',
      'usage.transit': 'Vị trí trung chuyển',
      'pickingType.incoming': 'Nhập kho',
      'pickingType.outgoing': 'Xuất kho',
      'pickingType.internal': 'Điều chuyển nội bộ',
      'backorder.ask': 'Hỏi khi hoàn tất',
      'backorder.always': 'Luôn tạo backorder',
      'backorder.never': 'Không tạo backorder',
      'ruleAction.pull': 'Kéo hàng từ vị trí khác',
      'ruleAction.push': 'Đẩy hàng sang vị trí khác',
      'ruleAction.pull_push': 'Kéo và đẩy hàng',
      'procureMethod.make_to_stock': 'Lấy từ tồn kho',
      'procureMethod.make_to_order': 'Cung ứng theo nhu cầu',
      'procureMethod.mts_else_mto': 'Ưu tiên tồn kho, thiếu thì cung ứng',
      'trigger.auto': 'Tự động',
      'trigger.manual': 'Thủ công',
      'record.location.stock': 'Tồn kho',
      'record.location.input': 'Đầu vào',
      'record.location.quality': 'Kiểm tra chất lượng',
      'record.location.output': 'Đầu ra',
      'record.location.pick': 'Lấy hàng',
      'record.location.pack': 'Đóng gói',
      'record.location.supplier': 'Nhà cung cấp',
      'record.location.customer': 'Khách hàng',
      'record.pickingType.incoming': 'Nhập kho',
      'record.pickingType.outgoing': 'Xuất kho',
      'record.pickingType.internal': 'Điều chuyển nội bộ',
      'record.pickingType.quality': 'Kiểm tra chất lượng',
      'record.pickingType.store': 'Nhập kho nội bộ',
      'record.pickingType.pick': 'Lấy hàng',
      'record.pickingType.pack': 'Đóng gói',
      'record.pickingType.adjustment': 'Điều chỉnh kiểm kê',
    },
    en: {
      'app.title': 'Inventory in admin',
      'app.summary': 'Manage multiple warehouses, stock, transfers, and procurement rules.',
      'app.category': 'System',
      'menu.app': 'Inventory',
      'menu.operations': 'Operations',
      'menu.transfers': 'Transfers',
      'menu.inventory': 'Stock',
      'menu.forecast': 'Forecast',
      'menu.replenishment': 'Replenishment',
      'menu.config': 'Configuration',
      'menu.warehouses': 'Warehouses',
      'menu.locations': 'Locations',
      'menu.pickingTypes': 'Operation types',
      'menu.lots': 'Lots / Serials',
      'menu.routes': 'Routes',
      inventory: 'Inventory',
      transfers: 'Transfers',
      warehouses: 'Warehouses',
      routes: 'Routes',
      locations: 'Locations',
      pickingTypes: 'Operation types',
      lots: 'Lots / Serials',
      replenishment: 'Replenishment',
      forecast: 'Stock forecast',
      transferDetail: 'Transfer details',
      'transfer.kicker': 'Inventory transfer',
      'transfer.collaboration.label': 'Transfer conversation and activities',
      'transfer.actions.label': 'Transfer actions',
      'transfer.summary.lines': 'Operation lines',
      'transfer.operations.title': 'Stock moves',
      'transfer.operations.hint': 'Review demand, completed quantities, and each line state.',
      'transfer.operations.empty': 'No stock moves yet',
      'transfer.operations.emptyHint': 'Add a product to begin processing this transfer.',
      'transfer.addMove.title': 'Add product',
      'transfer.addMove.hint': 'Set the product, unit, and quantity to move.',
      'transfer.recordDone.title': 'Record processing',
      'transfer.recordDone.hint': 'Enter the completed quantity and a lot or serial when required.',
      routeDetail: 'Route rules',
      'col.name': 'Name',
      'col.kind': 'Kind',
      'col.state': 'State',
      'col.detail': 'Detail',
      empty: 'No data yet.',
      emptyHint: 'Create the first record to begin.',
      'error.invalid': 'The submitted data is invalid. Please review it.',
      'action.create': 'Create',
      'action.apply': 'Apply inventory adjustment',
      'action.addMove': 'Add product line',
      'action.confirm': 'Confirm',
      'action.assign': 'Reserve',
      'action.validate': 'Validate',
      'action.validateCreateBackorder': 'Validate and create backorder',
      'action.validateNoBackorder': 'Validate without backorder',
      'action.recordDone': 'Record completed quantity',
      'action.cancel': 'Cancel',
      'action.addRule': 'Add rule',
      'action.calculate': 'Calculate forecast',
      'action.run': 'Run replenishment',
      'adjustment.title': 'Inventory adjustment',
      'field.productId': 'Variant ID',
      'field.location': 'Location',
      'field.inventoryLocation': 'Inventory location',
      'field.uom': 'Unit of measure',
      'field.lot': 'Lot / Serial',
      'field.counted': 'Counted quantity',
      'field.reference': 'Reference',
      'field.operationType': 'Operation type',
      'field.scheduledDate': 'Scheduled date',
      'field.demand': 'Demand',
      'field.operationLine': 'Operation line',
      'field.doneQuantity': 'Completed quantity',
      'field.code': 'Code',
      'field.receptionSteps': 'Receipt steps',
      'field.deliverySteps': 'Delivery steps',
      'field.usage': 'Usage',
      'field.warehouse': 'Warehouse',
      'field.parentLocation': 'Parent location',
      'field.sourceLocation': 'Source location',
      'field.destinationLocation': 'Destination location',
      'field.backorder': 'Create backorder',
      'field.lotSerial': 'Lot / Serial number',
      'field.note': 'Note',
      'field.sequence': 'Sequence',
      'field.ruleAction': 'Action',
      'field.procureMethod': 'Procurement method',
      'field.trigger': 'Trigger',
      'field.minQuantity': 'Minimum quantity',
      'field.maxQuantity': 'Maximum quantity',
      'field.replenishmentUom': 'Replenishment unit',
      'field.route': 'Route',
      'forecast.onHand': 'On hand',
      'forecast.incoming': 'Incoming',
      'forecast.outgoing': 'Outgoing',
      'forecast.value': 'Forecasted',
      'state.draft': 'Draft',
      'state.waiting': 'Waiting',
      'state.confirmed': 'Confirmed',
      'state.partially_available': 'Partially available',
      'state.reserved': 'Reserved',
      'state.assigned': 'Ready',
      'state.done': 'Done',
      'state.cancel': 'Cancelled',
      'kind.quant': 'Stock by location',
      'kind.transfer': 'Transfer',
      'kind.move': 'Stock move',
      'kind.move-line': 'Operation line',
      'kind.warehouse': 'Warehouse',
      'kind.lot': 'Lot / Serial',
      'kind.route': 'Route',
      'kind.internal': 'Internal',
      'kind.view': 'Location group',
      'kind.supplier': 'Vendor',
      'kind.customer': 'Customer',
      'kind.inventory': 'Inventory loss',
      'kind.production': 'Production',
      'kind.transit': 'Transit',
      'kind.incoming': 'Receipt',
      'kind.outgoing': 'Delivery',
      'kind.pull': 'Pull',
      'kind.push': 'Push',
      'kind.pull_push': 'Pull and push',
      'kind.auto': 'Automatic',
      'kind.manual': 'Manual',
      'receptionSteps.one_step': 'Receive goods directly',
      'receptionSteps.two_steps': 'Receive goods in input and then stock',
      'receptionSteps.three_steps': 'Input, quality, then stock',
      'deliverySteps.ship_only': 'Deliver goods directly',
      'deliverySteps.pick_ship': 'Pick then deliver',
      'deliverySteps.pick_pack_ship': 'Pick, pack, then deliver',
      'usage.internal': 'Internal location',
      'usage.view': 'Location group',
      'usage.supplier': 'Vendor location',
      'usage.customer': 'Customer location',
      'usage.inventory': 'Inventory loss location',
      'usage.production': 'Production location',
      'usage.transit': 'Transit location',
      'pickingType.incoming': 'Receipt',
      'pickingType.outgoing': 'Delivery',
      'pickingType.internal': 'Internal transfer',
      'backorder.ask': 'Ask when validating',
      'backorder.always': 'Always create a backorder',
      'backorder.never': 'Never create a backorder',
      'ruleAction.pull': 'Pull from another location',
      'ruleAction.push': 'Push to another location',
      'ruleAction.pull_push': 'Pull and push',
      'procureMethod.make_to_stock': 'Take from stock',
      'procureMethod.make_to_order': 'Trigger another rule',
      'procureMethod.mts_else_mto': 'Use stock, trigger rule for the rest',
      'trigger.auto': 'Automatic',
      'trigger.manual': 'Manual',
      'record.location.stock': 'Stock',
      'record.location.input': 'Input',
      'record.location.quality': 'Quality',
      'record.location.output': 'Output',
      'record.location.pick': 'Pick',
      'record.location.pack': 'Pack',
      'record.location.supplier': 'Vendor',
      'record.location.customer': 'Customer',
      'record.pickingType.incoming': 'Receipts',
      'record.pickingType.outgoing': 'Delivery Orders',
      'record.pickingType.internal': 'Internal Transfers',
      'record.pickingType.quality': 'Quality Control',
      'record.pickingType.store': 'Store',
      'record.pickingType.pick': 'Pick',
      'record.pickingType.pack': 'Pack',
      'record.pickingType.adjustment': 'Inventory Adjustments',
    },
  },
  fills: {
    'stock_backend:picking.editor': `{% island "stock.editor" %}`,
  },
})
