import { defineModule } from 'ketjs'
import { routes } from './routes.ts'

export default defineModule({
  name: 'stock_backend',
  version: '0.1.0',
  depends: ['stock', 'backend'],
  install: 'auto',
  app: true,
  title: 'Kho trong quản trị',
  summary: 'Warehouse, tồn kho, dịch chuyển và routes.',
  category: 'Hệ thống',
  routes,
  menus: {
    stock: { label: 'menu.app', icon: 'warehouse', sequence: 30 },
    'stock.operations': { parent: 'stock', label: 'menu.operations', sequence: 10 },
    'stock.transfers': {
      parent: 'stock.operations',
      label: 'menu.transfers',
      path: '/admin/transfers',
      needs: 'stock.listPickings',
    },
    'stock.inventory': {
      parent: 'stock.operations',
      label: 'menu.inventory',
      path: '/admin/inventory',
      needs: 'stock.listQuants',
    },
    'stock.forecast': {
      parent: 'stock.operations',
      label: 'menu.forecast',
      path: '/admin/forecast',
      needs: 'stock.forecast',
    },
    'stock.replenishment': {
      parent: 'stock.operations',
      label: 'menu.replenishment',
      path: '/admin/replenishment',
      needs: 'stock.listOrderpoints',
    },
    'stock.config': { parent: 'stock', label: 'menu.config', sequence: 20 },
    'stock.warehouses': {
      parent: 'stock.config',
      label: 'menu.warehouses',
      path: '/admin/warehouses',
      needs: 'stock.listWarehouses',
    },
    'stock.locations': {
      parent: 'stock.config',
      label: 'menu.locations',
      path: '/admin/locations',
      needs: 'stock.listLocations',
    },
    'stock.pickingTypes': {
      parent: 'stock.config',
      label: 'menu.pickingTypes',
      path: '/admin/picking-types',
      needs: 'stock.listPickingTypes',
    },
    'stock.lots': {
      parent: 'stock.config',
      label: 'menu.lots',
      path: '/admin/lots',
      needs: 'stock.listLots',
    },
    'stock.routes': {
      parent: 'stock.config',
      label: 'menu.routes',
      path: '/admin/stock-routes',
      needs: 'stock.listRoutes',
    },
  },
  messages: {
    vi: {
      'menu.app': 'Kho',
      'menu.operations': 'Vận hành',
      'menu.transfers': 'Dịch chuyển',
      'menu.inventory': 'Tồn kho',
      'menu.forecast': 'Dự báo',
      'menu.replenishment': 'Bổ sung hàng',
      'menu.config': 'Cấu hình',
      'menu.warehouses': 'Kho hàng',
      'menu.locations': 'Vị trí',
      'menu.pickingTypes': 'Loại hoạt động',
      'menu.lots': 'Lô / Sê-ri',
      'menu.routes': 'Routes',
      inventory: 'Tồn kho',
      transfers: 'Dịch chuyển',
      warehouses: 'Kho hàng',
      routes: 'Routes',
      locations: 'Vị trí kho',
      pickingTypes: 'Loại hoạt động',
      lots: 'Lô / Sê-ri',
      replenishment: 'Bổ sung hàng',
      forecast: 'Dự báo tồn kho',
      transferDetail: 'Chi tiết dịch chuyển',
      routeDetail: 'Quy tắc route',
      'col.name': 'Tên',
      'col.kind': 'Loại',
      'col.state': 'Trạng thái',
      'col.detail': 'Chi tiết',
      empty: 'Chưa có dữ liệu.',
      emptyHint: 'Tạo bản ghi đầu tiên để bắt đầu.',
      'error.invalid': 'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại.',
      'action.create': 'Tạo mới',
      'action.apply': 'Áp dụng kiểm kê',
      'action.addMove': 'Thêm dòng hàng',
      'action.confirm': 'Xác nhận',
      'action.assign': 'Giữ hàng',
      'action.validate': 'Hoàn tất',
      'action.cancel': 'Hủy',
      'action.addRule': 'Thêm quy tắc',
      'action.calculate': 'Tính dự báo',
      'action.run': 'Chạy bổ sung',
      'adjustment.title': 'Điều chỉnh tồn kho',
      'field.productId': 'ID biến thể',
      'field.location': 'Vị trí',
      'field.inventoryLocation': 'Vị trí kiểm kê',
      'field.uom': 'Đơn vị tính',
      'field.lot': 'Lô / Sê-ri',
      'field.counted': 'Số lượng đếm được',
      'field.reference': 'Tham chiếu',
      'field.operationType': 'Loại hoạt động',
      'field.scheduledDate': 'Ngày dự kiến',
      'field.demand': 'Nhu cầu',
      'field.code': 'Mã',
      'field.receptionSteps': 'Các bước nhận hàng',
      'field.deliverySteps': 'Các bước giao hàng',
      'field.usage': 'Cách sử dụng',
      'field.warehouse': 'Kho hàng',
      'field.parentLocation': 'Vị trí cha',
      'field.sourceLocation': 'Vị trí nguồn',
      'field.destinationLocation': 'Vị trí đích',
      'field.backorder': 'Tạo backorder',
      'field.lotSerial': 'Số lô / sê-ri',
      'field.note': 'Ghi chú',
      'field.sequence': 'Thứ tự',
      'field.ruleAction': 'Hành động',
      'field.procureMethod': 'Phương thức cung ứng',
      'field.trigger': 'Kích hoạt',
      'field.minQuantity': 'Tồn tối thiểu',
      'field.maxQuantity': 'Tồn tối đa',
      'field.replenishmentUom': 'Đơn vị bổ sung',
      'field.route': 'Route',
      'forecast.onHand': 'Tồn thực tế',
      'forecast.incoming': 'Sắp nhận',
      'forecast.outgoing': 'Sắp xuất',
      'forecast.value': 'Dự báo',
    },
    en: {
      'menu.app': 'Inventory',
      'menu.operations': 'Operations',
      'menu.transfers': 'Transfers',
      'menu.inventory': 'Stock',
      'menu.forecast': 'Forecast',
      'menu.replenishment': 'Replenishment',
      'menu.config': 'Configuration',
      'menu.warehouses': 'Warehouses',
      'menu.locations': 'Locations',
      'menu.pickingTypes': 'Operation types',
      'menu.lots': 'Lots / Serials',
      'menu.routes': 'Routes',
      inventory: 'Inventory',
      transfers: 'Transfers',
      warehouses: 'Warehouses',
      routes: 'Routes',
      locations: 'Locations',
      pickingTypes: 'Operation types',
      lots: 'Lots / Serials',
      replenishment: 'Replenishment',
      forecast: 'Stock forecast',
      transferDetail: 'Transfer details',
      routeDetail: 'Route rules',
      'col.name': 'Name',
      'col.kind': 'Kind',
      'col.state': 'State',
      'col.detail': 'Detail',
      empty: 'No data yet.',
      emptyHint: 'Create the first record to begin.',
      'error.invalid': 'The submitted data is invalid. Please review it.',
      'action.create': 'Create',
      'action.apply': 'Apply inventory adjustment',
      'action.addMove': 'Add product line',
      'action.confirm': 'Confirm',
      'action.assign': 'Reserve',
      'action.validate': 'Validate',
      'action.cancel': 'Cancel',
      'action.addRule': 'Add rule',
      'action.calculate': 'Calculate forecast',
      'action.run': 'Run replenishment',
      'adjustment.title': 'Inventory adjustment',
      'field.productId': 'Variant ID',
      'field.location': 'Location',
      'field.inventoryLocation': 'Inventory location',
      'field.uom': 'Unit of measure',
      'field.lot': 'Lot / Serial',
      'field.counted': 'Counted quantity',
      'field.reference': 'Reference',
      'field.operationType': 'Operation type',
      'field.scheduledDate': 'Scheduled date',
      'field.demand': 'Demand',
      'field.code': 'Code',
      'field.receptionSteps': 'Receipt steps',
      'field.deliverySteps': 'Delivery steps',
      'field.usage': 'Usage',
      'field.warehouse': 'Warehouse',
      'field.parentLocation': 'Parent location',
      'field.sourceLocation': 'Source location',
      'field.destinationLocation': 'Destination location',
      'field.backorder': 'Create backorder',
      'field.lotSerial': 'Lot / Serial number',
      'field.note': 'Note',
      'field.sequence': 'Sequence',
      'field.ruleAction': 'Action',
      'field.procureMethod': 'Procurement method',
      'field.trigger': 'Trigger',
      'field.minQuantity': 'Minimum quantity',
      'field.maxQuantity': 'Maximum quantity',
      'field.replenishmentUom': 'Replenishment unit',
      'field.route': 'Route',
      'forecast.onHand': 'On hand',
      'forecast.incoming': 'Incoming',
      'forecast.outgoing': 'Outgoing',
      'forecast.value': 'Forecasted',
    },
  },
})
