import { defineModule } from 'ketjs'
import { routes } from './routes.ts'

export default defineModule({
  name: 'stock_backend',
  version: '0.1.0',
  depends: ['stock', 'backend'],
  install: 'auto',
  app: true,
  title: 'Kho trong quản trị',
  summary: 'Warehouse, tồn kho, dịch chuyển và routes.',
  category: 'Hệ thống',
  routes,
  menus: {
    stock: { label: 'menu.app', icon: 'warehouse', sequence: 30 },
    'stock.operations': { parent: 'stock', label: 'menu.operations', sequence: 10 },
    'stock.transfers': {
      parent: 'stock.operations',
      label: 'menu.transfers',
      path: '/admin/transfers',
      needs: 'stock.listPickings',
    },
    'stock.inventory': {
      parent: 'stock.operations',
      label: 'menu.inventory',
      path: '/admin/inventory',
      needs: 'stock.listQuants',
    },
    'stock.config': { parent: 'stock', label: 'menu.config', sequence: 20 },
    'stock.warehouses': {
      parent: 'stock.config',
      label: 'menu.warehouses',
      path: '/admin/warehouses',
      needs: 'stock.listWarehouses',
    },
    'stock.routes': {
      parent: 'stock.config',
      label: 'menu.routes',
      path: '/admin/stock-routes',
      needs: 'stock.listRoutes',
    },
  },
  messages: {
    vi: {
      'menu.app': 'Kho',
      'menu.operations': 'Vận hành',
      'menu.transfers': 'Dịch chuyển',
      'menu.inventory': 'Tồn kho',
      'menu.config': 'Cấu hình',
      'menu.warehouses': 'Kho hàng',
      'menu.routes': 'Routes',
      inventory: 'Tồn kho',
      transfers: 'Dịch chuyển',
      warehouses: 'Kho hàng',
      routes: 'Routes',
      'col.name': 'Tên',
      'col.kind': 'Loại',
      'col.state': 'Trạng thái',
      'col.detail': 'Chi tiết',
      empty: 'Chưa có dữ liệu.',
      emptyHint: 'Tạo bản ghi đầu tiên để bắt đầu.',
    },
    en: {
      'menu.app': 'Inventory',
      'menu.operations': 'Operations',
      'menu.transfers': 'Transfers',
      'menu.inventory': 'Stock',
      'menu.config': 'Configuration',
      'menu.warehouses': 'Warehouses',
      'menu.routes': 'Routes',
      inventory: 'Inventory',
      transfers: 'Transfers',
      warehouses: 'Warehouses',
      routes: 'Routes',
      'col.name': 'Name',
      'col.kind': 'Kind',
      'col.state': 'State',
      'col.detail': 'Detail',
      empty: 'No data yet.',
      emptyHint: 'Create the first record to begin.',
    },
  },
})
