import { defineModule } from '@ketvietlab/ketjs'
import { routes } from './routes.ts'

export default defineModule({
  name: 'hr_backend',
  version: '0.1.0',
  depends: ['hr', 'backend'],
  install: 'auto',
  app: true,
  title: 'Nhân sự trong quản trị',
  summary: 'Hồ sơ, ca xoay và nghỉ phép.',
  category: 'Nhân sự',
  routes,
  menus: {
    hr: {
      label: 'menu.app',
      icon: 'users',
      path: '/admin/hr',
      sequence: 40,
      needs: 'hr.employee.manageList',
    },
    'hr.roster': {
      parent: 'hr',
      label: 'menu.roster',
      path: '/admin/hr/roster',
      sequence: 10,
      needs: 'hr.roster.manageList',
    },
    'hr.leaves': {
      parent: 'hr',
      label: 'menu.leaves',
      path: '/admin/hr/leaves',
      sequence: 20,
      needs: 'hr.leave.manageList',
    },
  },
  messages: {
    vi: {
      'app.title': 'Nhân sự trong quản trị',
      'app.summary': 'Hồ sơ, ca xoay và nghỉ phép.',
      'app.category': 'Nhân sự',
      'menu.app': 'Nhân sự',
      'menu.roster': 'Lịch ca',
      'menu.leaves': 'Nghỉ phép',
      'employees.title': 'Nhân viên',
      'employees.create': 'Thêm nhân viên',
      'roster.title': 'Lịch ca',
      'roster.generate': 'Sinh lịch tuần',
      'roster.week': 'Tuần',
      'roster.hint': 'Ca xoay được sinh idempotent và chỉ sửa khi lịch ở trạng thái nháp.',
      'roster.reopenReason': 'Điều chỉnh lịch đã phát hành',
      'leaves.title': 'Duyệt nghỉ phép',
      'field.code': 'Mã',
      'field.name': 'Tên',
      'field.partnerId': 'Partner ID',
      'field.userId': 'User ID',
      'field.branchId': 'Chi nhánh',
      'field.timezone': 'Múi giờ',
      'field.startDate': 'Ngày vào làm',
      'field.state': 'Trạng thái',
      'field.weekStart': 'Thứ Hai đầu tuần',
      'field.employee': 'Nhân viên',
      'field.date': 'Ngày',
      'field.startAt': 'Bắt đầu',
      'field.stopAt': 'Kết thúc',
      'field.days': 'Số ngày',
      'field.actions': 'Thao tác',
      'action.create': 'Tạo nhân viên',
      'action.generate': 'Sinh lịch',
      'action.publish': 'Phát hành',
      'action.reopen': 'Mở lại',
      'action.approve': 'Duyệt',
      'action.reject': 'Từ chối',
      'state.active': 'Đang làm việc',
      'state.archived': 'Đã lưu trữ',
      'state.draft': 'Nháp',
      'state.published': 'Đã phát hành',
      'state.requested': 'Chờ duyệt',
      'state.approved': 'Đã duyệt',
      'state.rejected': 'Từ chối',
      'empty.employees': 'Chưa có nhân viên',
      'empty.employeesHint': 'Tạo nhân viên đầu tiên từ một Partner loại cá nhân.',
      'empty.shifts': 'Chưa có ca',
      'empty.shiftsHint': 'Gán chu kỳ cho nhân viên rồi sinh lại lịch.',
      'empty.leaves': 'Không có yêu cầu nghỉ',
      'empty.leavesHint': 'Yêu cầu từ nhân viên sẽ xuất hiện tại đây.',
      'error.invalid': 'Không thể lưu dữ liệu.',
    },
    en: {
      'app.title': 'HR in admin',
      'app.summary': 'Employee records, rotating shifts, and leave.',
      'app.category': 'Human Resources',
      'menu.app': 'Human resources',
      'menu.roster': 'Shift roster',
      'menu.leaves': 'Leave',
      'employees.title': 'Employees',
      'employees.create': 'Add employee',
      'roster.title': 'Shift roster',
      'roster.generate': 'Generate weekly roster',
      'roster.week': 'Week',
      'roster.hint': 'Rotating shifts generate idempotently and can only change while the roster is draft.',
      'roster.reopenReason': 'Adjust a published roster',
      'leaves.title': 'Leave approvals',
      'field.code': 'Code',
      'field.name': 'Name',
      'field.partnerId': 'Partner ID',
      'field.userId': 'User ID',
      'field.branchId': 'Branch',
      'field.timezone': 'Timezone',
      'field.startDate': 'Start date',
      'field.state': 'Status',
      'field.weekStart': 'Week Monday',
      'field.employee': 'Employee',
      'field.date': 'Date',
      'field.startAt': 'Starts',
      'field.stopAt': 'Stops',
      'field.days': 'Days',
      'field.actions': 'Actions',
      'action.create': 'Create employee',
      'action.generate': 'Generate',
      'action.publish': 'Publish',
      'action.reopen': 'Reopen',
      'action.approve': 'Approve',
      'action.reject': 'Reject',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'state.draft': 'Draft',
      'state.published': 'Published',
      'state.requested': 'Requested',
      'state.approved': 'Approved',
      'state.rejected': 'Rejected',
      'empty.employees': 'No employees',
      'empty.employeesHint': 'Create the first employee from a person Partner.',
      'empty.shifts': 'No shifts',
      'empty.shiftsHint': 'Assign a rotation and generate the roster again.',
      'empty.leaves': 'No leave requests',
      'empty.leavesHint': 'Employee requests appear here.',
      'error.invalid': 'The data could not be saved.',
    },
  },
})

export { employeesScreen, leavesScreen, rosterScreen } from './screens.tsx'
