// The packaged KetSuite application declaration. Keeping this beside the
// modules lets both the repository app and the public CLI run the exact same
// composition instead of maintaining two module lists.

import { defineApp, sqliteStore } from '@ketvietlab/ketjs'
import type { OpenStore } from '@ketvietlab/ketjs'
import * as suite from './index.ts'
import backend from './modules/backend/index.ts'

export const createKetsuiteApp = (openStore: OpenStore = sqliteStore) =>
  defineApp({
    name: 'ketsuite',
    modules: [
      suite.website,
      suite.websiteMenu,
      suite.websiteSeo,
      suite.websiteSearch,
      suite.websiteForm,
      suite.websiteBackend,
      suite.websiteHospitality,
      suite.websiteRetail,
      suite.address,
      suite.partner,
      suite.company,
      suite.hr,
      suite.attendance,
      suite.hrBackend,
      suite.attendanceBackend,
      suite.storage,
      suite.user,
      suite.oauth,
      suite.userBackend,
      suite.oauthBackend,
      suite.mail,
      suite.mailBackend,
      suite.mailTransport,
      suite.mailTransportBackend,
      suite.mailInbound,
      suite.mailInboundBackend,
      suite.activity,
      suite.activityBackend,
      suite.calendar,
      suite.calendarActivity,
      suite.calendarBackend,
      suite.calendarMailTransport,
      suite.uom,
      suite.product,
      suite.productMedia,
      suite.pricing,
      suite.stock,
      suite.account,
      suite.purchase,
      suite.sale,
      suite.pos,
      suite.loyalty,
      suite.loyaltySale,
      suite.loyaltyPos,
      suite.crm,
      suite.crmSale,
      suite.crmWebsite,
      suite.accountPartner,
      suite.addressBackend,
      suite.partnerBackend,
      suite.companyBackend,
      suite.accountPartnerBackend,
      suite.productBackend,
      suite.pricingBackend,
      suite.stockBackend,
      suite.productMailBackend,
      suite.productVariantMailBackend,
      suite.stockMailBackend,
      suite.stockLotMailBackend,
      suite.productActivityBackend,
      suite.productVariantActivityBackend,
      suite.stockActivityBackend,
      suite.stockLotActivityBackend,
      suite.stockMailInbound,
      suite.accountBackend,
      suite.accountMailBackend,
      suite.accountActivityBackend,
      suite.purchaseBackend,
      suite.saleBackend,
      suite.saleMailBackend,
      suite.saleActivityBackend,
      suite.posBackend,
      suite.loyaltyBackend,
      suite.crmBackend,
      backend,
      suite.hospitalityCore,
    ],
    theme: suite.paperTheme,
    themes: [suite.hospitalityTheme, suite.retailTheme],
    datastore: 'main',
    worker: {
      queues: { default: 10, maintenance: 2, mail: 5 },
    },
    serve: {
      openStore,
      defaults: {
        sqliteFile: '.ket/ketsuite.db',
        defaultLocale: 'vi',
        fallbackLocale: 'vi',
        defaultTimezone: 'Asia/Ho_Chi_Minh',
      },
      bootstrap: [
        'website',
        'website_menu',
        'website_form',
        'website_backend',
        'website_hospitality',
        'website_retail',
        'theme_paper',
        'theme_hospitality',
        'theme_retail',
        'backend',
        'address',
        'product',
        'product_media',
        'pricing',
        'stock',
        'account',
        'purchase',
        'sale',
        'pos',
        'loyalty',
        'loyalty_sale',
        'loyalty_pos',
        'loyalty_backend',
        'crm',
        'crm_sale',
        'crm_website',
        'crm_backend',
        'user',
        'oauth',
        'user_backend',
        'oauth_backend',
        'storage',
        'hr',
        'attendance',
        'hospitality_core',
        'mail',
        'mail_transport',
        'mail_inbound',
        'activity',
        'calendar',
      ],
      sessions: { anonymous: { company: 'default' } },
      resolveSession: suite.resolveUserSession,
      permissions: (ctx, userId) =>
        ctx
          .callUnchecked('user.permitted', { userId }, new URL('http://x/'), { headers: {} } as never)
          .then((result) =>
            (result as { superuser: boolean; functions?: string[] }).superuser
              ? null
              : (result as { functions: string[] }).functions,
          ),
      pages: {
        siteResolve: 'website.resolveSite',
        resolve: 'website.getEntryByPath',
        region: 'website.page',
        notFound: 'website.page.notFound',
        siteTitle: 'KetSuite',
      },
    },
  })

export const ketsuite = createKetsuiteApp()
export const apps = [ketsuite]
