import { defineModule } from 'ketjs'
import { routes } from './routes.ts'
import { menus } from './menus.ts'

/**
 * The catalogue, in the admin — kept out of `product`.
 *
 * `product` must not depend on `backend`. A catalogue is a catalogue whether or
 * not this deployment ships an admin UI, and requiring one would mean a headless
 * API could not have products. But a screen in the admin genuinely needs both.
 *
 * So it is a bridge, and it installs itself once both sides are there — what
 * `install: 'auto'` was built for, and what Odoo does with `sale_stock` and its
 * kin. Install only product and there is no screen and no link; install the admin
 * too and both appear without anyone asking.
 *
 * It owns the page as well as the link. A bridge that contributed only a button
 * would be a bridge that ships a link to a 404.
 */
export default defineModule({
  name: 'product_backend',
  version: '0.1.0',
  depends: ['product_media', 'backend'],
  install: 'auto',
  app: true,
  title: 'Sản phẩm trong quản trị',
  summary: 'Màn hình danh mục sản phẩm và lối vào từ thanh điều hướng.',
  category: 'Hệ thống',
  routes,
  menus,
  joints: {
    'template.media': { props: { templateId: 'id' } },
    'variant.media': { props: { productId: 'id' } },
  },
  messages: {
    vi: {
      'app.title': 'Sản phẩm trong quản trị',
      'app.summary': 'Màn hình danh mục sản phẩm và lối vào từ thanh điều hướng.',
      'app.category': 'Hệ thống',
      'menu.app': 'Sản phẩm',
      'menu.catalogue': 'Danh mục',
      'menu.templates': 'Mẫu sản phẩm',
      'menu.attributes': 'Thuộc tính',
      'chrome.search': 'Tìm sản phẩm…',
      openCatalogue: 'Mở danh mục',
      'screen.title': 'Danh mục sản phẩm',
      'screen.empty.message': 'Chưa có sản phẩm nào.',
      'screen.empty.hint': 'Tạo mẫu sản phẩm đầu tiên để bắt đầu.',
      'col.name': 'Tên',
      'col.type': 'Loại',
      'col.uom': 'Đơn vị',
      'col.variants': 'Biến thể',
      'col.category': 'Nhóm',
      'col.sequence': 'Thứ tự',
      'col.state': 'Trạng thái',
      'state.active': 'Đang hoạt động',
      'state.archived': 'Đã lưu trữ',
      'type.goods': 'Hàng hoá',
      'type.service': 'Dịch vụ',
      'media.title': 'Hình ảnh',
      'media.description': 'Ảnh chính và thư viện ảnh của sản phẩm.',
      'media.unavailable': 'Chưa kết nối dịch vụ hình ảnh.',
      'media.empty': 'Chưa có hình ảnh.',
      'media.loading': 'Đang tải hình ảnh',
      'media.error': 'Không thể tải hình ảnh',
      'media.retry': 'Vui lòng thử lại khi dịch vụ hình ảnh hoạt động.',
      'media.primary': 'Đặt làm ảnh chính',
      'media.up': 'Dịch lên',
      'media.down': 'Dịch xuống',
      'media.remove': 'Xóa ảnh',
      'media.choose': 'Chọn ảnh',
      'media.add': 'Thêm ảnh',
      'detail.information': 'Thông tin sản phẩm',
      'action.create': 'Tạo mới',
      'action.save': 'Lưu',
      'action.cancel': 'Hủy',
      'action.add': 'Thêm',
      'create.title': 'Tạo sản phẩm',
      'error.invalid': 'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại.',
      'field.name': 'Tên',
      'field.type': 'Loại',
      'field.uom': 'Đơn vị tính',
      'field.category': 'Danh mục',
      'field.listPrice': 'Giá bán',
      'field.saleOk': 'Có thể bán',
      'field.purchaseOk': 'Có thể mua',
      'field.isStorable': 'Theo dõi tồn kho',
      'field.tracking': 'Truy xuất',
      'tracking.none': 'Không theo dõi',
      'tracking.lot': 'Theo lô',
      'tracking.serial': 'Theo số sê-ri duy nhất',
      'field.description': 'Mô tả',
      'field.defaultCode': 'Mã nội bộ',
      'field.barcode': 'Mã vạch',
      'field.weight': 'Khối lượng',
      'field.volume': 'Thể tích',
      'field.standardPrice': 'Giá vốn',
      'field.uomBarcode': 'Mã vạch theo đơn vị',
      'variants.title': 'Biến thể',
      'variants.generate': 'Sinh biến thể',
      'variants.empty': 'Chưa có biến thể.',
      'attributes.title': 'Thuộc tính sản phẩm',
      'attributes.lines': 'Dòng thuộc tính',
      'attributes.linesHint': 'Nhập ID các giá trị, phân cách bằng dấu phẩy.',
      'attributes.attribute': 'Thuộc tính',
      'attributes.values': 'Giá trị',
      'attributes.valuesHint': 'Ví dụ: red, blue',
      'attributes.displayType': 'Kiểu hiển thị',
      'attributes.createVariant': 'Tạo biến thể',
      'attributes.always': 'Luôn tạo',
      'attributes.never': 'Không tạo',
      'attributes.noValues': 'Chưa có giá trị',
      'attributes.valueName': 'Tên giá trị',
      'displayType.radio': 'Nút chọn',
      'displayType.pills': 'Nút dạng thẻ',
      'displayType.select': 'Danh sách chọn',
      'displayType.color': 'Màu sắc',
      'displayType.multi': 'Chọn nhiều',
      'createVariant.always': 'Luôn tạo biến thể',
      'createVariant.no_variant': 'Không tạo biến thể',
    },
    en: {
      'app.title': 'Products in admin',
      'app.summary': 'The catalogue screen, and the way into it.',
      'app.category': 'System',
      'menu.app': 'Products',
      'menu.catalogue': 'Catalogue',
      'menu.templates': 'Templates',
      'menu.attributes': 'Attributes',
      'chrome.search': 'Search products…',
      openCatalogue: 'Open catalogue',
      'screen.title': 'Product catalogue',
      'screen.empty.message': 'No products yet.',
      'screen.empty.hint': 'Create the first template to begin.',
      'col.name': 'Name',
      'col.type': 'Type',
      'col.uom': 'Unit',
      'col.variants': 'Variants',
      'col.category': 'Category',
      'col.sequence': 'Sequence',
      'col.state': 'State',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'type.goods': 'Goods',
      'type.service': 'Service',
      'media.title': 'Images',
      'media.description': 'Primary image and product gallery.',
      'media.unavailable': 'The image service is not connected.',
      'media.empty': 'No images yet.',
      'media.loading': 'Loading images',
      'media.error': 'Images could not be loaded',
      'media.retry': 'Try again when the image service is available.',
      'media.primary': 'Set as primary',
      'media.up': 'Move up',
      'media.down': 'Move down',
      'media.remove': 'Remove image',
      'media.choose': 'Choose image',
      'media.add': 'Add image',
      'detail.information': 'Product information',
      'action.create': 'Create',
      'action.save': 'Save',
      'action.cancel': 'Cancel',
      'action.add': 'Add',
      'create.title': 'Create product',
      'error.invalid': 'The submitted data is invalid. Please review it.',
      'field.name': 'Name',
      'field.type': 'Type',
      'field.uom': 'Unit of measure',
      'field.category': 'Category',
      'field.listPrice': 'Sales price',
      'field.saleOk': 'Can be sold',
      'field.purchaseOk': 'Can be purchased',
      'field.isStorable': 'Track inventory',
      'field.tracking': 'Tracking',
      'tracking.none': 'No tracking',
      'tracking.lot': 'By lots',
      'tracking.serial': 'By unique serial number',
      'field.description': 'Description',
      'field.defaultCode': 'Internal reference',
      'field.barcode': 'Barcode',
      'field.weight': 'Weight',
      'field.volume': 'Volume',
      'field.standardPrice': 'Cost',
      'field.uomBarcode': 'Unit barcode',
      'variants.title': 'Variants',
      'variants.generate': 'Generate variants',
      'variants.empty': 'No variants yet.',
      'attributes.title': 'Product attributes',
      'attributes.lines': 'Attribute lines',
      'attributes.linesHint': 'Enter value IDs separated by commas.',
      'attributes.attribute': 'Attribute',
      'attributes.values': 'Values',
      'attributes.valuesHint': 'For example: red, blue',
      'attributes.displayType': 'Display type',
      'attributes.createVariant': 'Variant creation',
      'attributes.always': 'Always',
      'attributes.never': 'Never',
      'attributes.noValues': 'No values yet',
      'attributes.valueName': 'Value name',
      'displayType.radio': 'Radio buttons',
      'displayType.pills': 'Pills',
      'displayType.select': 'Select',
      'displayType.color': 'Color',
      'displayType.multi': 'Multiple choice',
      'createVariant.always': 'Always create variants',
      'createVariant.no_variant': 'Never create variants',
    },
  },
  fills: {
    // KTL, addressing joints by name — the same language a storefront theme uses.
    'backend:app-card.actions': `{% if app.name == 'product' %}<a data-ui="app-action" href="/admin/products">{{ 'product_backend.openCatalogue' | _ }}</a>{% endif %}`,
  },
})

export { productsScreen, productDetailScreen } from './screens.ts'
export type { TemplateRow } from './screens.ts'
