import { defineModule } from 'ketjs'
import { menus } from './menus.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'website_backend',
  version: '0.1.0',
  app: true,
  install: 'auto',
  depends: ['backend', 'website', 'website_form', 'website_menu', 'website_seo'],
  title: 'Website trong quản trị',
  summary: 'Quản trị đa website, nội dung, revision, taxonomy, media, menu và biểu mẫu.',
  category: 'Hệ thống',
  routes,
  menus,
  messages: {
    vi: {
      'app.title': 'Website trong quản trị',
      'app.summary': 'Quản trị đa website, nội dung, revision, taxonomy, media, menu và biểu mẫu.',
      'app.category': 'Hệ thống',
      'menu.app': 'Website',
      'menu.pages': 'Trang',
      'menu.posts': 'Bài viết',
      'menu.taxonomies': 'Phân loại',
      'menu.media': 'Thư viện',
      'menu.menus': 'Menu',
      'menu.forms': 'Biểu mẫu',
      'menu.configuration': 'Cấu hình',
      'menu.sites': 'Website',
      'sites.title': 'Các website',
      'sites.newTitle': 'Website mới',
      'sites.eyebrow': 'Đa website',
      'sites.formHint': 'Mỗi website có locale và theme KTL riêng; có thể dùng domain riêng.',
      'sites.empty': 'Chưa có website nào.',
      'sites.emptyHint': 'Tạo website đầu tiên để bắt đầu biên tập nội dung.',
      'content.title': 'Nội dung website',
      'content.newTitle': 'Nội dung mới',
      'content.eyebrow': 'Trình biên tập',
      'content.formHint':
        'Nội dung và layout được lưu dưới dạng dữ liệu có schema và tự tạo revision khi lưu.',
      'content.empty': 'Website này chưa có nội dung.',
      'content.emptyHint': 'Tạo trang hoặc bài viết đầu tiên.',
      'content.noSite': 'Chưa có website để biên tập.',
      'content.noSiteHint': 'Tạo website trước rồi quay lại màn hình nội dung.',
      'pages.title': 'Trang',
      'pages.newTitle': 'Trang mới',
      'pages.formHint': 'Trang là nội dung tĩnh, có đường dẫn và bố cục riêng.',
      'posts.title': 'Bài viết',
      'posts.newTitle': 'Bài viết mới',
      'posts.formHint': 'Bài viết là nội dung xuất bản theo dòng thời gian và có thể gắn chuyên mục, thẻ.',
      'publish.title': 'Xuất bản',
      'publish.hint': 'Xuất bản revision hiện tại. Bản nháp sau đó không làm thay đổi nội dung đang phục vụ.',
      'revisions.title': 'Lịch sử phiên bản',
      'revisions.empty': 'Chưa có revision.',
      'revisions.emptyHint': 'Revision đầu tiên xuất hiện khi lưu nội dung.',
      'preview.title': 'Liên kết xem trước',
      'preview.hint': 'Token chỉ đọc này hết hạn sau 15 phút và trỏ đúng revision hiện tại.',
      'preview.token': 'Token',
      'preview.expires': 'Hết hạn',
      'taxonomies.title': 'Chuyên mục và thẻ',
      'taxonomies.newTitle': 'Term mới',
      'taxonomies.formHint': 'Tạo và sắp xếp chuyên mục hoặc thẻ riêng cho từng website.',
      'taxonomies.empty': 'Chưa có term nào.',
      'taxonomies.emptyHint': 'Term được quản lý riêng theo từng website.',
      'media.title': 'Thư viện media',
      'media.newTitle': 'Thêm media',
      'media.formHint': 'Liên kết tệp trong Storage với metadata dùng riêng cho website.',
      'media.empty': 'Chưa có media.',
      'media.emptyHint': 'Tải tệp qua Storage rồi thêm alt text theo website.',
      'menus.title': 'Menu website',
      'menus.newTitle': 'Mục menu mới',
      'menus.formHint': 'Tạo liên kết, thứ tự và quan hệ cha con trong menu website.',
      'menus.empty': 'Chưa có mục menu.',
      'menus.emptyHint': 'Menu được sắp xếp và cô lập theo website.',
      'forms.title': 'Biểu mẫu website',
      'forms.newTitle': 'Biểu mẫu mới',
      'forms.formHint': 'Khai báo field bằng JSON; submission được kiểm tra schema, honeypot và rate limit.',
      'forms.empty': 'Chưa có biểu mẫu.',
      'forms.emptyHint': 'Tạo biểu mẫu liên hệ hoặc nhận yêu cầu đầu tiên.',
      'submissions.title': 'Dữ liệu biểu mẫu',
      'submissions.empty': 'Chưa có submission.',
      'submissions.emptyHint': 'Dữ liệu hợp lệ sẽ xuất hiện ở đây.',
      'action.newSite': 'Tạo website',
      'action.pages': 'Mở trang',
      'action.save': 'Lưu',
      'action.cancel': 'Hủy',
      'action.switchSite': 'Chuyển website',
      'action.newEntry': 'Tạo nội dung',
      'action.newPage': 'Tạo trang',
      'action.newPost': 'Tạo bài viết',
      'action.newTerm': 'Tạo chuyên mục hoặc thẻ',
      'action.deleteTerm': 'Xóa term',
      'action.newMedia': 'Thêm media',
      'action.deleteMedia': 'Xóa metadata media',
      'action.newMenuItem': 'Tạo mục menu',
      'action.deleteMenuItem': 'Xóa mục menu',
      'action.taxonomies': 'Phân loại',
      'action.saveDraft': 'Lưu bản nháp',
      'action.publish': 'Xuất bản ngay',
      'action.revisions': 'Revision',
      'action.preview': 'Xem trước',
      'action.backToEntry': 'Quay lại nội dung',
      'action.backToContent': 'Quay lại danh sách',
      'action.newForm': 'Tạo biểu mẫu',
      'field.site': 'Website',
      'field.name': 'Tên nội bộ',
      'field.siteTitle': 'Tên hiển thị',
      'field.locale': 'Ngôn ngữ',
      'field.theme': 'Theme KTL',
      'field.active': 'Đang hoạt động',
      'field.title': 'Tiêu đề',
      'field.slug': 'Slug',
      'field.path': 'Đường dẫn',
      'field.type': 'Loại nội dung',
      'field.status': 'Trạng thái',
      'field.excerpt': 'Tóm tắt',
      'field.fields': 'Trường nội dung (JSON)',
      'field.fieldsHint': 'Các field phải khớp schema của loại nội dung đã chọn.',
      'field.layout': 'Layout section (JSON)',
      'field.layoutHint': 'Mảng section có type và settings; Ket kiểm tra với registry module.',
      'field.version': 'Phiên bản',
      'field.kind': 'Loại',
      'field.author': 'Tác giả',
      'field.createdAt': 'Thời điểm',
      'field.taxonomy': 'Taxonomy',
      'field.parent': 'Cấp cha',
      'field.description': 'Mô tả',
      'field.attachment': 'Tệp',
      'field.alt': 'Alt text',
      'field.caption': 'Chú thích',
      'field.width': 'Chiều rộng',
      'field.height': 'Chiều cao',
      'field.size': 'Kích thước',
      'field.label': 'Nhãn',
      'field.href': 'Liên kết',
      'field.position': 'Thứ tự',
      'field.notifyTo': 'Email nhận thông báo',
      'field.successMessage': 'Thông báo thành công',
      'field.schema': 'Schema field (JSON)',
      'field.payload': 'Dữ liệu',
      'field.consent': 'Đồng ý',
      'state.active': 'Đang hoạt động',
      'state.inactive': 'Tạm dừng',
      'state.draft': 'Bản nháp',
      'state.published': 'Đã xuất bản',
      'state.scheduled': 'Đã lên lịch',
      'state.trash': 'Thùng rác',
      'state.yes': 'Có',
      'state.no': 'Không',
      'error.invalid': 'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại.',
      'error.invalidJson': 'JSON không hợp lệ',
      'error.notFound': 'Không tìm thấy dữ liệu.',
    },
    en: {
      'app.title': 'Website administration',
      'app.summary': 'Manage multiple sites, content, revisions, taxonomies, media, menus and forms.',
      'app.category': 'System',
      'menu.app': 'Website',
      'menu.pages': 'Pages',
      'menu.posts': 'Posts',
      'menu.taxonomies': 'Taxonomies',
      'menu.media': 'Media',
      'menu.menus': 'Menus',
      'menu.forms': 'Forms',
      'menu.configuration': 'Configuration',
      'menu.sites': 'Sites',
      'sites.title': 'Sites',
      'sites.newTitle': 'New site',
      'sites.eyebrow': 'Multisite',
      'sites.formHint': 'Each site has its own locale and KTL theme, and can use a separate domain.',
      'sites.empty': 'No sites yet.',
      'sites.emptyHint': 'Create the first site to start editing content.',
      'content.title': 'Website content',
      'content.newTitle': 'New content',
      'content.eyebrow': 'Editor',
      'content.formHint':
        'Content and layout are schema-backed data; every save creates an immutable revision.',
      'content.empty': 'This site has no content yet.',
      'content.emptyHint': 'Create the first page or post.',
      'content.noSite': 'There is no site to edit.',
      'content.noSiteHint': 'Create a site first, then return to content.',
      'pages.title': 'Pages',
      'pages.newTitle': 'New page',
      'pages.formHint': 'Pages are static content with their own path and layout.',
      'posts.title': 'Posts',
      'posts.newTitle': 'New post',
      'posts.formHint': 'Posts are chronological content that can use categories and tags.',
      'publish.title': 'Publish',
      'publish.hint': 'Publish the current revision. Later drafts do not change the live version.',
      'revisions.title': 'Revision history',
      'revisions.empty': 'No revisions yet.',
      'revisions.emptyHint': 'The first revision appears after content is saved.',
      'preview.title': 'Preview link',
      'preview.hint': 'This read-only token expires after 15 minutes and targets the current revision.',
      'preview.token': 'Token',
      'preview.expires': 'Expires',
      'taxonomies.title': 'Categories and tags',
      'taxonomies.newTitle': 'New term',
      'taxonomies.formHint': 'Create and organize site-specific categories or tags.',
      'taxonomies.empty': 'No terms yet.',
      'taxonomies.emptyHint': 'Terms are managed independently for each site.',
      'media.title': 'Media library',
      'media.newTitle': 'Add media',
      'media.formHint': 'Link a Storage attachment to site-specific media metadata.',
      'media.empty': 'No media yet.',
      'media.emptyHint': 'Upload through Storage, then add site-specific alt text.',
      'menus.title': 'Website menus',
      'menus.newTitle': 'New menu item',
      'menus.formHint': 'Create links, ordering and parent-child relationships for the website menu.',
      'menus.empty': 'No menu items yet.',
      'menus.emptyHint': 'Menus are ordered and isolated by site.',
      'forms.title': 'Website forms',
      'forms.newTitle': 'New form',
      'forms.formHint':
        'Declare fields as JSON; submissions use schema validation, a honeypot and rate limiting.',
      'forms.empty': 'No forms yet.',
      'forms.emptyHint': 'Create the first contact or enquiry form.',
      'submissions.title': 'Form submissions',
      'submissions.empty': 'No submissions yet.',
      'submissions.emptyHint': 'Valid submissions will appear here.',
      'action.newSite': 'Create site',
      'action.pages': 'Open pages',
      'action.save': 'Save',
      'action.cancel': 'Cancel',
      'action.switchSite': 'Switch site',
      'action.newEntry': 'Create content',
      'action.newPage': 'Create page',
      'action.newPost': 'Create post',
      'action.newTerm': 'Create category or tag',
      'action.deleteTerm': 'Delete term',
      'action.newMedia': 'Add media',
      'action.deleteMedia': 'Delete media metadata',
      'action.newMenuItem': 'Create menu item',
      'action.deleteMenuItem': 'Delete menu item',
      'action.taxonomies': 'Taxonomies',
      'action.saveDraft': 'Save draft',
      'action.publish': 'Publish now',
      'action.revisions': 'Revisions',
      'action.preview': 'Preview',
      'action.backToEntry': 'Back to content',
      'action.backToContent': 'Back to list',
      'action.newForm': 'Create form',
      'field.site': 'Site',
      'field.name': 'Internal name',
      'field.siteTitle': 'Display title',
      'field.locale': 'Language',
      'field.theme': 'KTL theme',
      'field.active': 'Active',
      'field.title': 'Title',
      'field.slug': 'Slug',
      'field.path': 'Path',
      'field.type': 'Content type',
      'field.status': 'Status',
      'field.excerpt': 'Excerpt',
      'field.fields': 'Content fields (JSON)',
      'field.fieldsHint': 'Fields must match the selected content-type schema.',
      'field.layout': 'Section layout (JSON)',
      'field.layoutHint':
        'An array of sections with type and settings; Ket validates it against the module registry.',
      'field.version': 'Version',
      'field.kind': 'Kind',
      'field.author': 'Author',
      'field.createdAt': 'Created',
      'field.taxonomy': 'Taxonomy',
      'field.parent': 'Parent',
      'field.description': 'Description',
      'field.attachment': 'Attachment',
      'field.alt': 'Alt text',
      'field.caption': 'Caption',
      'field.width': 'Width',
      'field.height': 'Height',
      'field.size': 'Size',
      'field.label': 'Label',
      'field.href': 'Link',
      'field.position': 'Position',
      'field.notifyTo': 'Notification email',
      'field.successMessage': 'Success message',
      'field.schema': 'Field schema (JSON)',
      'field.payload': 'Payload',
      'field.consent': 'Consent',
      'state.active': 'Active',
      'state.inactive': 'Inactive',
      'state.draft': 'Draft',
      'state.published': 'Published',
      'state.scheduled': 'Scheduled',
      'state.trash': 'Trash',
      'state.yes': 'Yes',
      'state.no': 'No',
      'error.invalid': 'The data is invalid. Check the form and try again.',
      'error.invalidJson': 'Invalid JSON',
      'error.notFound': 'The record was not found.',
    },
  },
})
