import { defineModule } from '@ketvietlab/ketjs'
import { menus } from './menus.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'website_backend',
  version: '0.1.0',
  depends: ['backend', 'website', 'website_form', 'website_menu', 'website_seo'],
  title: 'Website trong quản trị',
  summary: 'Quản trị đa website, nội dung, revision, taxonomy, media, menu và biểu mẫu.',
  category: 'Hệ thống',
  routes,
  menus,
  messages: {
    vi: {
      'app.title': 'Website trong quản trị',
      'app.summary': 'Quản trị đa website, nội dung, revision, taxonomy, media, menu và biểu mẫu.',
      'app.category': 'Hệ thống',
      'menu.app': 'Website',
      'menu.pages': 'Trang',
      'menu.posts': 'Bài viết',
      'menu.taxonomies': 'Phân loại',
      'menu.media': 'Thư viện',
      'menu.menus': 'Menu',
      'menu.forms': 'Biểu mẫu',
      'menu.configuration': 'Cấu hình',
      'menu.sites': 'Website',
      'menu.redirects': 'Chuyển hướng',
      'sites.title': 'Các website',
      'sites.newTitle': 'Website mới',
      'sites.eyebrow': 'Đa website',
      'sites.formHint': 'Mỗi website có locale và theme KTL riêng; có thể dùng domain riêng.',
      'sites.empty': 'Chưa có website nào.',
      'sites.emptyHint': 'Tạo website đầu tiên để bắt đầu biên tập nội dung.',
      'content.title': 'Nội dung website',
      'content.newTitle': 'Nội dung mới',
      'content.eyebrow': 'Trình biên tập',
      'content.formHint':
        'Nội dung và layout được lưu dưới dạng dữ liệu có schema và tự tạo revision khi lưu.',
      'content.empty': 'Website này chưa có nội dung.',
      'content.emptyHint': 'Tạo trang hoặc bài viết đầu tiên.',
      'content.noSite': 'Chưa có website để biên tập.',
      'content.noSiteHint': 'Tạo website trước rồi quay lại màn hình nội dung.',
      'pages.title': 'Trang',
      'pages.newTitle': 'Trang mới',
      'pages.formHint': 'Trang là nội dung tĩnh, có đường dẫn và bố cục riêng.',
      'posts.title': 'Bài viết',
      'posts.newTitle': 'Bài viết mới',
      'posts.formHint': 'Bài viết là nội dung xuất bản theo dòng thời gian và có thể gắn chuyên mục, thẻ.',
      'publish.title': 'Xuất bản',
      'publish.hint': 'Xuất bản revision hiện tại. Bản nháp sau đó không làm thay đổi nội dung đang phục vụ.',
      'revisions.title': 'Lịch sử phiên bản',
      'revisions.empty': 'Chưa có revision.',
      'revisions.emptyHint': 'Revision đầu tiên xuất hiện khi lưu nội dung.',
      'revisions.compare': 'So sánh',
      'revisions.compareHint': 'Xem một bản đã đổi gì, không cần khôi phục nó ra để nhìn.',
      'revisions.from': 'Từ bản',
      'revisions.to': 'Đến bản',
      'revisions.change': 'Thay đổi',
      'revisions.section': 'Section',
      'revisions.where': 'Vị trí',
      'revisions.detail': 'Chi tiết',
      'revisions.noChanges': 'Hai bản này giống nhau',
      'revisions.noChangesHint': 'Không section nào được thêm, bớt, dời hay sửa.',
      'revisions.unidentified': 'So sánh không đầy đủ',
      'revisions.unidentifiedHint':
        'Một trong hai bản được lưu trước khi section có danh tính, nên mọi thứ hiện ra như thêm mới và xóa đi.',
      'preview.title': 'Liên kết xem trước',
      'preview.hint': 'Token chỉ đọc này hết hạn sau 15 phút và trỏ đúng revision hiện tại.',
      'preview.token': 'Token',
      'preview.expires': 'Hết hạn',
      'taxonomies.title': 'Chuyên mục và thẻ',
      'taxonomies.newTitle': 'Term mới',
      'taxonomies.formHint': 'Tạo và sắp xếp chuyên mục hoặc thẻ riêng cho từng website.',
      'taxonomies.empty': 'Chưa có term nào.',
      'taxonomies.emptyHint': 'Term được quản lý riêng theo từng website.',
      'media.title': 'Thư viện media',
      'media.newTitle': 'Thêm media',
      'media.formHint': 'Liên kết tệp trong Storage với metadata dùng riêng cho website.',
      'media.empty': 'Chưa có media.',
      'media.emptyHint': 'Tải tệp qua Storage rồi thêm alt text theo website.',
      'menus.title': 'Menu website',
      'menus.newTitle': 'Mục menu mới',
      'menus.formHint': 'Tạo liên kết, thứ tự và quan hệ cha con trong menu website.',
      'menus.empty': 'Chưa có mục menu.',
      'menus.emptyHint': 'Menu được sắp xếp và cô lập theo website.',
      'menus.dangling': 'Có liên kết không dẫn tới đâu',
      'menus.danglingHint': 'Những mục sau trỏ tới đường dẫn không trang nào phục vụ:',
      'action.preflight': 'Kiểm tra trước khi xuất bản',
      'preflight.title': 'Kiểm tra trước khi xuất bản',
      'preflight.clean': 'Không có trang nào hỏng',
      'preflight.broken': 'Có trang không vẽ được',
      'preflight.checked': 'Số trang đã kiểm',
      'preflight.why': 'Lý do',
      'preflight.capped': 'Chưa quét hết website',
      'preflight.cappedHint':
        'Website lớn hơn một lượt quét, nên kết quả này không trả lời được cho toàn bộ.',
      'forms.title': 'Biểu mẫu website',
      'forms.newTitle': 'Biểu mẫu mới',
      'forms.editTitle': 'Sửa biểu mẫu',
      'submission.title': 'Lượt gửi',
      'submission.answers': 'Câu trả lời',
      'submission.answer': 'Nội dung',
      'submission.noAnswers': 'Không còn nội dung',
      'submission.noAnswersHint':
        'Nội dung đã bị xóa theo thời hạn lưu, hoặc lượt gửi này không có câu trả lời nào.',
      'submission.consentHint':
        'Văn bản dưới đây được lưu nguyên văn lúc khách đồng ý, vì biểu mẫu là một hàng có thể sửa.',
      'submission.holdHint': 'Một lượt gửi đang được giữ sẽ không bị xóa theo thời hạn lưu.',
      'submission.holdReason': 'Lý do giữ lại',
      'submission.holdReasonHint':
        'Để trống nghĩa là bỏ giữ. Bỏ giữ không xóa ngay, chỉ trả nó về hàng đợi thông thường.',
      'submission.audit': 'Ai đã xem',
      'submission.auditHint': 'Mỗi lần mở, xuất, giữ hay xóa đều được ghi lại tại đây.',
      'submission.action': 'Hành động',
      'submission.actor': 'Người thực hiện',
      'submission.reason': 'Lý do',
      'submission.noAudit': 'Chưa có ai xem',
      'submission.noAuditHint': 'Lần mở đầu tiên sẽ xuất hiện ở đây.',
      'submission.purgedHint': 'Nội dung đã bị xóa. Bản ghi đồng ý được giữ lại.',
      'submissions.export': 'Xuất dữ liệu',
      'submissions.exportHint':
        'Chỉ những trường được nêu tên mới rời khỏi hệ thống, và danh sách đó được ghi vào sổ.',
      'submissions.exportFields': 'Trường cần xuất',
      'submissions.exportFieldsHint':
        'Tên trường, cách nhau bằng dấu phẩy. Trường không có trong biểu mẫu sẽ bị từ chối.',
      'submissions.purge': 'Xóa nội dung quá hạn',
      'submissions.purgeHint':
        'Xóa nội dung của những lượt gửi đã quá thời hạn lưu và không bị giữ. Không hoàn tác được.',
      'submissions.purgeConfirm': 'Tôi hiểu việc này không hoàn tác được',
      'submissions.purgeUnconfirmed': 'Hãy xác nhận trước khi xóa.',
      'action.open': 'Mở',
      'action.remove': 'Gỡ',
      'action.backToSite': 'Về website',
      'members.title': 'Người phụ trách website',
      'members.add': 'Thêm người',
      'members.addHint':
        'Vai trò quyết định người này sửa được gì. Quyền cấp rồi mà không ai rà lại là quyền sống lâu hơn lý do của nó.',
      'members.user': 'Người dùng',
      'members.role': 'Vai trò',
      'members.empty': 'Chưa có ai được phân công',
      'members.emptyHint': 'Khi chưa có thành viên nào, chỉ lời gọi nội bộ mới sửa được website này.',
      'role.administrator': 'Quản trị',
      'role.editor': 'Biên tập',
      'role.author': 'Tác giả',
      'role.contributor': 'Cộng tác',
      'domains.title': 'Tên miền',
      'domains.add': 'Thêm tên miền',
      'domains.addHint': 'Tên miền chính là địa chỉ mà canonical và sitemap công bố ra ngoài.',
      'domains.host': 'Tên miền',
      'domains.primary': 'Chính',
      'domains.primaryHint': 'Mỗi website chỉ một tên miền chính.',
      'domains.redirect': 'Chuyển về tên miền chính',
      'domains.empty': 'Chưa có tên miền',
      'domains.emptyHint': 'Website vẫn phục vụ được, nhưng canonical không có địa chỉ để công bố.',
      'redirects.title': 'Chuyển hướng',
      'redirects.add': 'Thêm chuyển hướng',
      'redirects.addHint': 'Giữ đường dẫn cũ còn sống sau khi sắp xếp lại nội dung.',
      'redirects.from': 'Từ đường dẫn',
      'redirects.to': 'Đến đường dẫn',
      'redirects.permanent': 'Vĩnh viễn',
      'redirects.permanentHint': 'Vĩnh viễn là 301 và trình duyệt sẽ nhớ. Tạm thời là 302.',
      'redirects.p301': '301',
      'redirects.p302': '302',
      'redirects.empty': 'Chưa có chuyển hướng',
      'redirects.emptyHint': 'Mọi đường dẫn cũ hiện trả về 404.',
      'index.title': 'Chỉ mục tìm kiếm',
      'index.current': 'Chỉ mục khớp nội dung đang live',
      'index.stale': 'Chỉ mục chưa theo kịp',
      'index.documents': 'Số tài liệu',
      'index.completedAt': 'Dựng xong lúc',
      'index.rebuild': 'Dựng lại ngay',
      'index.rebuilt': 'Đã dựng xong',
      'index.rebuilding': 'Đã dựng một phần, phần còn lại sẽ chạy tiếp',
      'index.written': 'Số tài liệu vừa ghi',
      'state.kept': 'Giữ lại',
      'forms.formHint': 'Khai báo field bằng JSON; submission được kiểm tra schema, honeypot và rate limit.',
      'forms.empty': 'Chưa có biểu mẫu.',
      'forms.emptyHint': 'Tạo biểu mẫu liên hệ hoặc nhận yêu cầu đầu tiên.',
      'submissions.title': 'Dữ liệu biểu mẫu',
      'submissions.empty': 'Chưa có submission.',
      'submissions.emptyHint': 'Dữ liệu hợp lệ sẽ xuất hiện ở đây.',
      'action.newSite': 'Tạo website',
      'action.pages': 'Mở trang',
      'action.save': 'Lưu',
      'action.cancel': 'Hủy',
      'action.switchSite': 'Chuyển website',
      'action.newEntry': 'Tạo nội dung',
      'action.newPage': 'Tạo trang',
      'action.newPost': 'Tạo bài viết',
      'action.newTerm': 'Tạo chuyên mục hoặc thẻ',
      'action.deleteTerm': 'Xóa term',
      'action.newMedia': 'Thêm media',
      'action.deleteMedia': 'Xóa metadata media',
      'action.newMenuItem': 'Tạo mục menu',
      'action.deleteMenuItem': 'Xóa mục menu',
      'action.taxonomies': 'Phân loại',
      'action.saveDraft': 'Lưu bản nháp',
      'action.publish': 'Xuất bản ngay',
      'action.revisions': 'Revision',
      'action.preview': 'Xem trước',
      'action.backToEntry': 'Quay lại nội dung',
      'action.backToContent': 'Quay lại danh sách',
      'action.newForm': 'Tạo biểu mẫu',
      'field.site': 'Website',
      'field.name': 'Tên nội bộ',
      'field.siteTitle': 'Tên hiển thị',
      'field.locale': 'Ngôn ngữ',
      'field.theme': 'Theme KTL',
      'field.active': 'Đang hoạt động',
      'field.title': 'Tiêu đề',
      'field.slug': 'Slug',
      'field.path': 'Đường dẫn',
      'field.type': 'Loại nội dung',
      'field.status': 'Trạng thái',
      'field.excerpt': 'Tóm tắt',
      'field.fields': 'Trường nội dung (JSON)',
      'field.fieldsHint': 'Các field phải khớp schema của loại nội dung đã chọn.',
      'field.layout': 'Layout section (JSON)',
      'field.layoutHint': 'Mảng section có type và settings; Ket kiểm tra với registry module.',
      'field.version': 'Phiên bản',
      'field.kind': 'Loại',
      'field.author': 'Tác giả',
      'field.createdAt': 'Thời điểm',
      'field.taxonomy': 'Taxonomy',
      'field.parent': 'Cấp cha',
      'field.description': 'Mô tả',
      'field.attachment': 'Tệp',
      'field.alt': 'Alt text',
      'field.caption': 'Chú thích',
      'field.width': 'Chiều rộng',
      'field.height': 'Chiều cao',
      'field.size': 'Kích thước',
      'field.label': 'Nhãn',
      'field.href': 'Liên kết',
      'field.position': 'Thứ tự',
      'field.notifyTo': 'Email nhận thông báo',
      'field.consentText': 'Thông báo quyền riêng tư',
      'field.summaryFields': 'Trường xem trước',
      'field.retentionDays': 'Thời hạn lưu (ngày)',
      'help.consentText':
        'Hiện cạnh ô đồng ý. Để trống nghĩa là biểu mẫu không hỏi đồng ý. Sửa văn bản này sẽ nâng version của biểu mẫu.',
      'help.summaryFields':
        'Tên trường, cách nhau bằng dấu phẩy, được phép hiện trong danh sách. Để trống thì danh sách không hiện câu trả lời nào.',
      'help.retentionDays':
        'Sau bấy nhiêu ngày, nội dung khách điền bị xóa còn bản ghi đồng ý được giữ. Để trống nghĩa là giữ lại.',
      'field.successMessage': 'Thông báo thành công',
      'field.schema': 'Schema field (JSON)',
      'field.payload': 'Dữ liệu',
      'field.summary': 'Xem trước',
      'field.hold': 'Giữ lại',
      'field.consent': 'Đồng ý',
      'state.active': 'Đang hoạt động',
      'state.inactive': 'Tạm dừng',
      'state.draft': 'Bản nháp',
      'state.published': 'Đã xuất bản',
      'state.scheduled': 'Đã lên lịch',
      'state.trash': 'Thùng rác',
      'state.yes': 'Có',
      'state.noPreview': 'Không hiển thị',
      'state.purged': 'Đã xóa nội dung',
      'state.no': 'Không',
      'error.invalid': 'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại.',
      'error.invalidJson': 'JSON không hợp lệ',
      'error.notFound': 'Không tìm thấy dữ liệu.',
    },
    en: {
      'app.title': 'Website administration',
      'app.summary': 'Manage multiple sites, content, revisions, taxonomies, media, menus and forms.',
      'app.category': 'System',
      'menu.app': 'Website',
      'menu.pages': 'Pages',
      'menu.posts': 'Posts',
      'menu.taxonomies': 'Taxonomies',
      'menu.media': 'Media',
      'menu.menus': 'Menus',
      'menu.forms': 'Forms',
      'menu.configuration': 'Configuration',
      'menu.sites': 'Sites',
      'menu.redirects': 'Redirects',
      'sites.title': 'Sites',
      'sites.newTitle': 'New site',
      'sites.eyebrow': 'Multisite',
      'sites.formHint': 'Each site has its own locale and KTL theme, and can use a separate domain.',
      'sites.empty': 'No sites yet.',
      'sites.emptyHint': 'Create the first site to start editing content.',
      'content.title': 'Website content',
      'content.newTitle': 'New content',
      'content.eyebrow': 'Editor',
      'content.formHint':
        'Content and layout are schema-backed data; every save creates an immutable revision.',
      'content.empty': 'This site has no content yet.',
      'content.emptyHint': 'Create the first page or post.',
      'content.noSite': 'There is no site to edit.',
      'content.noSiteHint': 'Create a site first, then return to content.',
      'pages.title': 'Pages',
      'pages.newTitle': 'New page',
      'pages.formHint': 'Pages are static content with their own path and layout.',
      'posts.title': 'Posts',
      'posts.newTitle': 'New post',
      'posts.formHint': 'Posts are chronological content that can use categories and tags.',
      'publish.title': 'Publish',
      'publish.hint': 'Publish the current revision. Later drafts do not change the live version.',
      'revisions.title': 'Revision history',
      'revisions.empty': 'No revisions yet.',
      'revisions.emptyHint': 'The first revision appears after content is saved.',
      'revisions.compare': 'Compare',
      'revisions.compareHint': 'See what a revision changed, without restoring it to find out.',
      'revisions.from': 'From',
      'revisions.to': 'To',
      'revisions.change': 'Change',
      'revisions.section': 'Section',
      'revisions.where': 'Where',
      'revisions.detail': 'Detail',
      'revisions.noChanges': 'These two are the same',
      'revisions.noChangesHint': 'No section was added, removed, moved or edited.',
      'revisions.unidentified': 'Incomplete comparison',
      'revisions.unidentifiedHint':
        'One of these was saved before sections carried identity, so everything reads as added and removed.',
      'preview.title': 'Preview link',
      'preview.hint': 'This read-only token expires after 15 minutes and targets the current revision.',
      'preview.token': 'Token',
      'preview.expires': 'Expires',
      'taxonomies.title': 'Categories and tags',
      'taxonomies.newTitle': 'New term',
      'taxonomies.formHint': 'Create and organize site-specific categories or tags.',
      'taxonomies.empty': 'No terms yet.',
      'taxonomies.emptyHint': 'Terms are managed independently for each site.',
      'media.title': 'Media library',
      'media.newTitle': 'Add media',
      'media.formHint': 'Link a Storage attachment to site-specific media metadata.',
      'media.empty': 'No media yet.',
      'media.emptyHint': 'Upload through Storage, then add site-specific alt text.',
      'menus.title': 'Website menus',
      'menus.newTitle': 'New menu item',
      'menus.formHint': 'Create links, ordering and parent-child relationships for the website menu.',
      'menus.empty': 'No menu items yet.',
      'menus.emptyHint': 'Menus are ordered and isolated by site.',
      'menus.dangling': 'Some links lead nowhere',
      'menus.danglingHint': 'These items point at a path no page serves:',
      'action.preflight': 'Check before publishing',
      'preflight.title': 'Check before publishing',
      'preflight.clean': 'No page would break',
      'preflight.broken': 'Some pages cannot be drawn',
      'preflight.checked': 'Pages checked',
      'preflight.why': 'Why',
      'preflight.capped': 'The whole site was not scanned',
      'preflight.cappedHint': 'This site is larger than one scan, so this answer does not cover all of it.',
      'forms.title': 'Website forms',
      'forms.newTitle': 'New form',
      'forms.editTitle': 'Edit form',
      'submission.title': 'Submission',
      'submission.answers': 'Answers',
      'submission.answer': 'Value',
      'submission.noAnswers': 'Nothing left to read',
      'submission.noAnswersHint':
        'The answers were erased by the retention window, or this submission had none.',
      'submission.consentHint':
        'Stored verbatim at the moment of agreement, because a form is one mutable row.',
      'submission.holdHint': 'A submission on hold is not erased by the retention window.',
      'submission.holdReason': 'Reason for the hold',
      'submission.holdReasonHint':
        'Blank releases the hold. Releasing does not erase; it returns the row to the ordinary queue.',
      'submission.audit': 'Who looked',
      'submission.auditHint': 'Every read, export, hold and erasure is written down here.',
      'submission.action': 'Action',
      'submission.actor': 'Who',
      'submission.reason': 'Reason',
      'submission.noAudit': 'Nobody has looked yet',
      'submission.noAuditHint': 'The first read will appear here.',
      'submission.purgedHint': 'The answers were erased. The consent record is kept.',
      'submissions.export': 'Export',
      'submissions.exportHint':
        'Only the fields named here leave the system, and that list is written into the record.',
      'submissions.exportFields': 'Fields to export',
      'submissions.exportFieldsHint':
        'Field names, comma separated. A field the form does not ask is refused.',
      'submissions.purge': 'Erase what is past its window',
      'submissions.purgeHint':
        'Erases the answers of submissions past the retention window that are not on hold. This cannot be undone.',
      'submissions.purgeConfirm': 'I understand this cannot be undone',
      'submissions.purgeUnconfirmed': 'Confirm before erasing.',
      'action.open': 'Open',
      'action.remove': 'Remove',
      'action.backToSite': 'Back to site',
      'members.title': 'Site members',
      'members.add': 'Add someone',
      'members.addHint':
        'The role decides what this person may change. A permission granted and never reviewed outlives its reason.',
      'members.user': 'User',
      'members.role': 'Role',
      'members.empty': 'Nobody is assigned yet',
      'members.emptyHint': 'With no members, only an internal call can change this site.',
      'role.administrator': 'Administrator',
      'role.editor': 'Editor',
      'role.author': 'Author',
      'role.contributor': 'Contributor',
      'domains.title': 'Domains',
      'domains.add': 'Add a domain',
      'domains.addHint': 'The primary domain is the address canonical URLs and the sitemap publish.',
      'domains.host': 'Host',
      'domains.primary': 'Primary',
      'domains.primaryHint': 'One primary per site.',
      'domains.redirect': 'Redirect to primary',
      'domains.empty': 'No domains yet',
      'domains.emptyHint': 'The site still serves, but canonical has no address to publish.',
      'redirects.title': 'Redirects',
      'redirects.add': 'Add a redirect',
      'redirects.addHint': 'Keeps an old path alive after content is rearranged.',
      'redirects.from': 'From path',
      'redirects.to': 'To path',
      'redirects.permanent': 'Permanent',
      'redirects.permanentHint': 'Permanent is a 301 and browsers remember it. Temporary is a 302.',
      'redirects.p301': '301',
      'redirects.p302': '302',
      'redirects.empty': 'No redirects yet',
      'redirects.emptyHint': 'Every old path currently answers 404.',
      'index.title': 'Search index',
      'index.current': 'The index matches what is live',
      'index.stale': 'The index has not caught up',
      'index.documents': 'Documents',
      'index.completedAt': 'Built at',
      'index.rebuild': 'Rebuild now',
      'index.rebuilt': 'Rebuilt',
      'index.rebuilding': 'Partly built; the rest continues on its own',
      'index.written': 'Documents written',
      'state.kept': 'Kept',
      'forms.formHint':
        'Declare fields as JSON; submissions use schema validation, a honeypot and rate limiting.',
      'forms.empty': 'No forms yet.',
      'forms.emptyHint': 'Create the first contact or enquiry form.',
      'submissions.title': 'Form submissions',
      'submissions.empty': 'No submissions yet.',
      'submissions.emptyHint': 'Valid submissions will appear here.',
      'action.newSite': 'Create site',
      'action.pages': 'Open pages',
      'action.save': 'Save',
      'action.cancel': 'Cancel',
      'action.switchSite': 'Switch site',
      'action.newEntry': 'Create content',
      'action.newPage': 'Create page',
      'action.newPost': 'Create post',
      'action.newTerm': 'Create category or tag',
      'action.deleteTerm': 'Delete term',
      'action.newMedia': 'Add media',
      'action.deleteMedia': 'Delete media metadata',
      'action.newMenuItem': 'Create menu item',
      'action.deleteMenuItem': 'Delete menu item',
      'action.taxonomies': 'Taxonomies',
      'action.saveDraft': 'Save draft',
      'action.publish': 'Publish now',
      'action.revisions': 'Revisions',
      'action.preview': 'Preview',
      'action.backToEntry': 'Back to content',
      'action.backToContent': 'Back to list',
      'action.newForm': 'Create form',
      'field.site': 'Site',
      'field.name': 'Internal name',
      'field.siteTitle': 'Display title',
      'field.locale': 'Language',
      'field.theme': 'KTL theme',
      'field.active': 'Active',
      'field.title': 'Title',
      'field.slug': 'Slug',
      'field.path': 'Path',
      'field.type': 'Content type',
      'field.status': 'Status',
      'field.excerpt': 'Excerpt',
      'field.fields': 'Content fields (JSON)',
      'field.fieldsHint': 'Fields must match the selected content-type schema.',
      'field.layout': 'Section layout (JSON)',
      'field.layoutHint':
        'An array of sections with type and settings; Ket validates it against the module registry.',
      'field.version': 'Version',
      'field.kind': 'Kind',
      'field.author': 'Author',
      'field.createdAt': 'Created',
      'field.taxonomy': 'Taxonomy',
      'field.parent': 'Parent',
      'field.description': 'Description',
      'field.attachment': 'Attachment',
      'field.alt': 'Alt text',
      'field.caption': 'Caption',
      'field.width': 'Width',
      'field.height': 'Height',
      'field.size': 'Size',
      'field.label': 'Label',
      'field.href': 'Link',
      'field.position': 'Position',
      'field.notifyTo': 'Notification email',
      'field.consentText': 'Privacy notice',
      'field.summaryFields': 'Preview fields',
      'field.retentionDays': 'Retention (days)',
      'help.consentText':
        'Shown beside the consent box. Blank means the form asks for no agreement. Editing this text advances the form version.',
      'help.summaryFields':
        'Field names, comma separated, allowed to appear in the list. Blank means the list shows no answers.',
      'help.retentionDays':
        'After this many days the answers are erased and the consent record is kept. Blank means kept.',
      'field.successMessage': 'Success message',
      'field.schema': 'Field schema (JSON)',
      'field.payload': 'Payload',
      'field.summary': 'Preview',
      'field.hold': 'Hold',
      'field.consent': 'Consent',
      'state.active': 'Active',
      'state.inactive': 'Inactive',
      'state.draft': 'Draft',
      'state.published': 'Published',
      'state.scheduled': 'Scheduled',
      'state.trash': 'Trash',
      'state.yes': 'Yes',
      'state.noPreview': 'Not shown',
      'state.purged': 'Erased',
      'state.no': 'No',
      'error.invalid': 'The data is invalid. Check the form and try again.',
      'error.invalidJson': 'Invalid JSON',
      'error.notFound': 'The record was not found.',
    },
  },
})
