import { defineModule } from 'ketjs'
import { menus } from './menus.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'partner_backend',
  version: '0.1.0',
  depends: ['partner', 'backend'],
  install: 'auto',
  app: true,
  title: 'Danh bạ đối tác',
  summary: 'Quản lý khách hàng, nhà cung cấp, liên hệ và địa chỉ.',
  category: 'Bán hàng',
  routes,
  menus,
  joints: { 'record.actions': { props: { partnerId: 'id', locale: 'text?' } } },
  messages: {
    vi: {
      'app.title': 'Danh bạ đối tác',
      'app.summary': 'Quản lý khách hàng, nhà cung cấp, liên hệ và địa chỉ.',
      'app.category': 'Bán hàng',
      'menu.app': 'Đối tác',
      'menu.directory': 'Danh bạ',
      'screen.title': 'Đối tác',
      'screen.empty': 'Chưa có đối tác nào',
      'screen.emptyHint': 'Tạo khách hàng, nhà cung cấp hoặc liên hệ đầu tiên.',
      'chrome.search': 'Tìm theo tên đối tác…',
      'filter.customers': 'Khách hàng',
      'filter.suppliers': 'Nhà cung cấp',
      'filter.includeArchived': 'Gồm đã lưu trữ',
      'filter.activeOnly': 'Chỉ đang hoạt động',
      'action.create': 'Tạo đối tác',
      'action.save': 'Lưu thông tin',
      'action.cancel': 'Hủy',
      'action.saveRoles': 'Lưu vai trò',
      'action.saveAddress': 'Lưu địa chỉ',
      'action.addAddress': 'Thêm địa chỉ',
      'action.saveTerms': 'Lưu điều khoản',
      'action.archive': 'Lưu trữ đối tác',
      'action.restore': 'Khôi phục đối tác',
      'create.title': 'Tạo đối tác',
      'detail.identity': 'Thông tin chính',
      'field.name': 'Tên',
      'field.kind': 'Loại',
      'field.parent': 'Tổ chức cha',
      'field.ref': 'Mã đối tác',
      'field.vat': 'Mã số thuế',
      'field.email': 'Email',
      'field.phone': 'Điện thoại',
      'field.lang': 'Ngôn ngữ',
      'field.state': 'Trạng thái',
      'state.active': 'Đang hoạt động',
      'state.archived': 'Đã lưu trữ',
      'state.title': 'Trạng thái hồ sơ',
      'roles.title': 'Vai trò nghiệp vụ',
      'roles.hint': 'Một đối tác có thể đồng thời là khách hàng, nhà cung cấp hoặc nhân viên.',
      'addresses.title': 'Địa chỉ',
      'addresses.hint': 'Mỗi mục đích chỉ có một địa chỉ mặc định.',
      'address.new': 'Thêm địa chỉ',
      'address.use': 'Mục đích',
      'address.street': 'Địa chỉ',
      'address.street2': 'Dòng địa chỉ 2',
      'address.city': 'Tỉnh/Thành phố',
      'address.state': 'Tỉnh/Bang',
      'address.zip': 'Mã bưu chính',
      'address.country': 'Quốc gia',
      'address.default': 'Mặc định',
      'terms.title': 'Điều khoản theo công ty',
      'terms.hint': 'Hạn mức và ghi chú áp dụng cho công ty đang hoạt động.',
      'terms.creditLimit': 'Hạn mức tín dụng',
      'terms.note': 'Ghi chú',
      'error.notFound': 'Không tìm thấy đối tác.',
    },
    en: {
      'app.title': 'Partner directory',
      'app.summary': 'Manage customers, suppliers, contacts and addresses.',
      'app.category': 'Sales',
      'menu.app': 'Partners',
      'menu.directory': 'Directory',
      'screen.title': 'Partners',
      'screen.empty': 'No partners yet',
      'screen.emptyHint': 'Create the first customer, supplier or contact.',
      'chrome.search': 'Search partner names…',
      'filter.customers': 'Customers',
      'filter.suppliers': 'Suppliers',
      'filter.includeArchived': 'Include archived',
      'filter.activeOnly': 'Active only',
      'action.create': 'Create partner',
      'action.save': 'Save information',
      'action.cancel': 'Cancel',
      'action.saveRoles': 'Save roles',
      'action.saveAddress': 'Save address',
      'action.addAddress': 'Add address',
      'action.saveTerms': 'Save terms',
      'action.archive': 'Archive partner',
      'action.restore': 'Restore partner',
      'create.title': 'Create partner',
      'detail.identity': 'Main information',
      'field.name': 'Name',
      'field.kind': 'Type',
      'field.parent': 'Parent organisation',
      'field.ref': 'Partner reference',
      'field.vat': 'Tax ID',
      'field.email': 'Email',
      'field.phone': 'Phone',
      'field.lang': 'Language',
      'field.state': 'Status',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'state.title': 'Record status',
      'roles.title': 'Business roles',
      'roles.hint': 'A partner may be a customer, supplier and employee at the same time.',
      'addresses.title': 'Addresses',
      'addresses.hint': 'Each purpose has one default address.',
      'address.new': 'Add address',
      'address.use': 'Purpose',
      'address.street': 'Street',
      'address.street2': 'Street line 2',
      'address.city': 'City',
      'address.state': 'State/Province',
      'address.zip': 'Postal code',
      'address.country': 'Country',
      'address.default': 'Default',
      'terms.title': 'Company terms',
      'terms.hint': 'The limit and note apply to the active company.',
      'terms.creditLimit': 'Credit limit',
      'terms.note': 'Note',
      'error.notFound': 'Partner not found.',
    },
  },
})

export { newPartnerScreen, partnerDetailScreen, partnersScreen } from './screens.ts'
