import { defineModule } from '@ketvietlab/ketjs'
import { menus } from './menus.ts'
import { routes } from './routes.ts'

export default defineModule({
  name: 'company_backend',
  version: '0.1.0',
  depends: ['company', 'user', 'partner_backend', 'backend'],
  install: 'auto',
  app: true,
  title: 'Công ty và chi nhánh',
  summary: 'Quản lý pháp nhân, cây chi nhánh và ngữ cảnh làm việc.',
  category: 'Hệ thống',
  routes,
  menus,
  messages: {
    vi: {
      'app.title': 'Công ty và chi nhánh',
      'app.summary': 'Quản lý pháp nhân, cây chi nhánh và ngữ cảnh làm việc.',
      'app.category': 'Hệ thống',
      'menu.companies': 'Công ty',
      'menu.hierarchy': 'Cây pháp nhân',
      'screen.title': 'Công ty',
      'screen.empty': 'Chưa có công ty nào',
      'screen.emptyHint': 'Tạo pháp nhân đầu tiên từ một đối tác loại công ty.',
      'filter.includeArchived': 'Gồm đã lưu trữ',
      'filter.activeOnly': 'Chỉ đang hoạt động',
      'action.create': 'Tạo công ty',
      'action.hierarchy': 'Xem cây pháp nhân',
      'action.save': 'Lưu',
      'action.manageAddress': 'Quản lý địa chỉ pháp lý',
      'action.cancel': 'Hủy',
      'action.archive': 'Lưu trữ công ty',
      'action.restore': 'Khôi phục công ty',
      'action.addBranch': 'Thêm chi nhánh',
      'action.archiveBranch': 'Lưu trữ chi nhánh',
      'action.restoreBranch': 'Khôi phục chi nhánh',
      'create.title': 'Tạo công ty',
      'detail.identity': 'Thông tin pháp nhân',
      'detail.identityHint': 'Tên, mã số thuế và địa chỉ được quản lý trên Partner đại diện.',
      'field.name': 'Tên',
      'field.code': 'Mã',
      'field.partner': 'Đối tác đại diện',
      'field.parent': 'Công ty mẹ',
      'field.currency': 'Tiền tệ',
      'field.state': 'Trạng thái',
      'field.kind': 'Loại',
      'field.branchParent': 'Chi nhánh cha',
      'option.selectPartner': 'Chọn đối tác công ty…',
      'option.noParent': 'Không có công ty mẹ',
      'state.title': 'Trạng thái hồ sơ',
      'state.active': 'Đang hoạt động',
      'state.archived': 'Đã lưu trữ',
      'branches.title': 'Chi nhánh vận hành',
      'branches.hint': 'Root branch được tạo cùng pháp nhân; các chi nhánh khác được cấp cho user rõ ràng.',
      'branches.empty': 'Chưa có chi nhánh',
      'branches.emptyHint': 'Root branch sẽ luôn tồn tại khi công ty được tạo hợp lệ.',
      'branch.root': 'Gốc / mặc định',
      'branch.operational': 'Vận hành',
      'branch.createTitle': 'Tạo chi nhánh',
      'branch.detail': 'Thông tin chi nhánh',
      'hierarchy.title': 'Cây pháp nhân',
      'context.title': 'Ngữ cảnh làm việc',
      'context.writeTitle': 'Công ty và chi nhánh đang ghi',
      'context.writeHint':
        'Một thao tác chỉ ghi vào đúng một công ty và một chi nhánh; các checkbox quyết định tập được đọc.',
      'context.activeCompany': 'Công ty đang hoạt động',
      'context.activeBranch': 'Chi nhánh đang hoạt động',
      'context.readCompany': 'Đọc công ty',
      'context.readBranch': 'Đọc chi nhánh',
      'context.apply': 'Áp dụng ngữ cảnh',
      'context.conflict': 'Session đã được đổi ở request khác. Hãy tải lại và thử lại.',
      'error.notFound': 'Không tìm thấy công ty.',
      'error.branchNotFound': 'Không tìm thấy chi nhánh.',
    },
    en: {
      'app.title': 'Companies and branches',
      'app.summary': 'Manage legal entities, branch trees and the working context.',
      'app.category': 'System',
      'menu.companies': 'Companies',
      'menu.hierarchy': 'Legal-entity tree',
      'screen.title': 'Companies',
      'screen.empty': 'No companies yet',
      'screen.emptyHint': 'Create the first legal entity from a company partner.',
      'filter.includeArchived': 'Include archived',
      'filter.activeOnly': 'Active only',
      'action.create': 'Create company',
      'action.hierarchy': 'View legal-entity tree',
      'action.save': 'Save',
      'action.manageAddress': 'Manage legal address',
      'action.cancel': 'Cancel',
      'action.archive': 'Archive company',
      'action.restore': 'Restore company',
      'action.addBranch': 'Add branch',
      'action.archiveBranch': 'Archive branch',
      'action.restoreBranch': 'Restore branch',
      'create.title': 'Create company',
      'detail.identity': 'Legal-entity information',
      'detail.identityHint': 'Name, tax ID and addresses are managed on the representative Partner.',
      'field.name': 'Name',
      'field.code': 'Code',
      'field.partner': 'Representative partner',
      'field.parent': 'Parent company',
      'field.currency': 'Currency',
      'field.state': 'Status',
      'field.kind': 'Type',
      'field.branchParent': 'Parent branch',
      'option.selectPartner': 'Select a company partner…',
      'option.noParent': 'No parent company',
      'state.title': 'Record status',
      'state.active': 'Active',
      'state.archived': 'Archived',
      'branches.title': 'Operational branches',
      'branches.hint':
        'The root branch is created with the legal entity; other branches are granted to users explicitly.',
      'branches.empty': 'No branches',
      'branches.emptyHint': 'A valid company always has its root branch.',
      'branch.root': 'Root / default',
      'branch.operational': 'Operational',
      'branch.createTitle': 'Create branch',
      'branch.detail': 'Branch information',
      'hierarchy.title': 'Legal-entity tree',
      'context.title': 'Working context',
      'context.writeTitle': 'Active write company and branch',
      'context.writeHint':
        'An operation writes to exactly one company and branch; the checkboxes define the readable sets.',
      'context.activeCompany': 'Active company',
      'context.activeBranch': 'Active branch',
      'context.readCompany': 'Read company',
      'context.readBranch': 'Read branch',
      'context.apply': 'Apply context',
      'context.conflict': 'The session changed in another request. Reload and try again.',
      'error.notFound': 'Company not found.',
      'error.branchNotFound': 'Branch not found.',
    },
  },
})

export { routes } from './routes.ts'
export {
  companiesScreen,
  companyFormScreen,
  branchFormScreen,
  hierarchyScreen,
  contextScreen,
} from './screens.tsx'
