import type { MenuDef } from '@ketvietlab/ketjs'

export const menus: Record<string, MenuDef> = {
  hospitality: { label: 'menu.app', icon: 'hotel', sequence: 10 },
  'hospitality.operations': { parent: 'hospitality', label: 'menu.operations', sequence: 10 },
  'hospitality.frontDesk': {
    parent: 'hospitality.operations',
    label: 'menu.frontDesk',
    path: '/admin/hospitality/front-desk',
    needs: 'hospitality_core.listStays',
    sequence: 10,
  },
  'hospitality.tapeChart': {
    parent: 'hospitality.operations',
    label: 'menu.tapeChart',
    path: '/admin/hospitality/tape-chart',
    needs: 'hospitality_core.getTapeChart',
    sequence: 20,
  },
  'hospitality.reservations': {
    parent: 'hospitality.operations',
    label: 'menu.reservations',
    path: '/admin/hospitality/reservations',
    needs: 'hospitality_core.listReservations',
    sequence: 30,
  },
  'hospitality.stays': {
    parent: 'hospitality.operations',
    label: 'menu.stays',
    path: '/admin/hospitality/stays',
    needs: 'hospitality_core.listStays',
    sequence: 40,
  },
  'hospitality.folios': {
    parent: 'hospitality.operations',
    label: 'menu.folios',
    path: '/admin/hospitality/folios',
    needs: 'hospitality_core.listFolios',
    sequence: 50,
  },
  'hospitality.services': {
    parent: 'hospitality.operations',
    label: 'menu.services',
    path: '/admin/hospitality/services',
    needs: 'hospitality_core.listExtraLines',
    sequence: 52,
  },
  'hospitality.nightAudit': {
    parent: 'hospitality.operations',
    label: 'menu.nightAudit',
    path: '/admin/hospitality/night-audit',
    needs: 'hospitality_core.listNightAudits',
    sequence: 54,
  },
  'hospitality.inventory': {
    parent: 'hospitality.operations',
    label: 'menu.inventory',
    path: '/admin/hospitality/inventory',
    needs: 'hospitality_core.listInventory',
    sequence: 55,
  },
  'hospitality.properties': {
    parent: 'hospitality.operations',
    label: 'menu.properties',
    path: '/admin/hospitality/properties',
    needs: 'hospitality_core.listProperties',
    sequence: 60,
  },
  'hospitality.rooms': {
    parent: 'hospitality.operations',
    label: 'menu.rooms',
    path: '/admin/hospitality/rooms',
    needs: 'hospitality_core.listRooms',
    sequence: 70,
  },
  'hospitality.housekeeping': { parent: 'hospitality', label: 'menu.housekeeping', sequence: 70 },
  'hospitality.cleaningTasks': {
    parent: 'hospitality.housekeeping',
    label: 'menu.cleaningTasks',
    path: '/admin/hospitality/housekeeping',
    needs: 'hospitality_core.listCleaningTasks',
    sequence: 10,
  },
  'hospitality.housekeepingRooms': {
    parent: 'hospitality.housekeeping',
    label: 'menu.housekeepingRooms',
    path: '/admin/hospitality/housekeeping/rooms',
    needs: 'hospitality_core.listRooms',
    sequence: 20,
  },
  'hospitality.compliance': { parent: 'hospitality', label: 'menu.compliance', sequence: 80 },
  'hospitality.stayNotices': {
    parent: 'hospitality.compliance',
    label: 'menu.stayNotices',
    path: '/admin/hospitality/stay-notices',
    needs: 'hospitality_core.listStayNotices',
    sequence: 10,
  },
  'hospitality.configuration': { parent: 'hospitality', label: 'menu.configuration', sequence: 90 },
  'hospitality.roomTypes': {
    parent: 'hospitality.configuration',
    label: 'menu.roomTypes',
    path: '/admin/hospitality/room-types',
    needs: 'hospitality_core.listRoomTypes',
    sequence: 10,
  },
  'hospitality.content': {
    parent: 'hospitality.configuration',
    label: 'menu.content',
    path: '/admin/hospitality/content',
    needs: 'hospitality_core.listContentImages',
    sequence: 12,
  },
  'hospitality.ratePlans': {
    parent: 'hospitality.configuration',
    label: 'menu.ratePlans',
    path: '/admin/hospitality/rate-plans',
    needs: 'hospitality_core.listRatePlans',
    sequence: 15,
  },
  'hospitality.amenities': {
    parent: 'hospitality.configuration',
    label: 'menu.amenities',
    path: '/admin/hospitality/amenities',
    needs: 'hospitality_core.listAmenities',
    sequence: 20,
  },
  'hospitality.policies': {
    parent: 'hospitality.configuration',
    label: 'menu.policies',
    path: '/admin/hospitality/policies',
    needs: 'hospitality_core.listCancellationPolicies',
    sequence: 30,
  },
}
