// The manifest becomes TypeScript declarations.
//
// This is how a field that module B adds to module A's model becomes visible, with
// its real type, to module C — without any module importing another's internals and
// without a compiler plugin. Node runs the code; tsc reads these declarations.

import { tsTypeOf } from '../kernel/types.ts'
import type { Manifest } from '../types.ts'

const pascal = (key: string): string =>
  key
    .split('.')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')

const tsInput = (spec: string): string => {
  const optional = spec.endsWith('?')
  const base = optional ? spec.slice(0, -1) : spec
  const map: Record<string, string> = {
    id: 'string',
    text: 'string',
    int: 'number',
    float: 'number',
    bool: 'boolean',
    json: 'unknown',
    datetime: 'string',
  }
  const t = base.startsWith('ref:') ? 'string' : (map[base] ?? 'unknown')
  return optional ? `${t} | undefined` : t
}

export function generateDts(manifest: Manifest): string {
  const out: string[] = []
  out.push('// GENERATED BY KET — do not edit. Run `ket types` to regenerate.')
  out.push('// Every field records the module that contributed it.')
  out.push('')

  for (const [key, model] of Object.entries(manifest.models)) {
    out.push(`export interface ${pascal(key)} {`)
    for (const [fname, f] of Object.entries(model.fields)) {
      if (f.by !== model.owner) out.push(`  /** contributed by module "${f.by}" */`)
      out.push(`  ${fname}: ${tsTypeOf(f)}`)
    }
    // Relations are optional on the type because they are optional in fact: they
    // are there only if the query asked to preload them, and the type says so
    // rather than pretending every row arrives complete.
    for (const [name, rel] of Object.entries(manifest.relations[key] ?? {})) {
      const target = pascal(rel.target)
      out.push(`  /** preload("${name}") — ${rel.kind} ${rel.target}, declared by "${rel.declaredBy}" */`)
      out.push(`  ${name}?: ${rel.kind === 'hasMany' ? `${target}[]` : `${target} | null`}`)
    }
    out.push('}')
    out.push('')
  }

  out.push('export interface KetModels {')
  for (const key of Object.keys(manifest.models)) out.push(`  ${JSON.stringify(key)}: ${pascal(key)}`)
  out.push('}')
  out.push('')

  for (const [key, view] of Object.entries(manifest.views)) {
    out.push(`/** view model exposed to themes by "${view.by}" (projection of ${view.of}) */`)
    out.push(`export interface ${pascal(key)}Drop {`)
    const model = manifest.models[view.of]
    for (const f of view.fields) {
      const field = model?.fields[f]
      out.push(`  readonly ${f}: ${field ? tsTypeOf(field) : 'unknown'}`)
    }
    out.push('}')
    out.push('')
  }

  out.push('export interface KetFunctions {')
  for (const [key, fn] of Object.entries(manifest.functions)) {
    const input = Object.entries(fn.input)
      .map(([n, t]) => `${n}${t.endsWith('?') ? '?' : ''}: ${tsInput(t)}`)
      .join('; ')
    const output = Object.keys(fn.output).length
      ? `{ ${Object.entries(fn.output)
          .map(([n, t]) => `${n}: ${tsInput(t)}`)
          .join('; ')} }`
      : 'unknown'
    out.push(
      `  ${JSON.stringify(key)}: { input: { ${input} }; output: ${output}; effects: ${fn.effects.map((e) => JSON.stringify(e)).join(' | ') || 'never'} }`,
    )
  }
  out.push('}')
  out.push('')

  out.push('export type KetClient = {')
  out.push(
    '  [K in keyof KetFunctions]: (args: KetFunctions[K]["input"]) => Promise<KetFunctions[K]["output"]>',
  )
  out.push('}')
  out.push('')
  out.push('export type JointKey =')
  const joints = Object.keys(manifest.joints)
  out.push(joints.length ? joints.map((j) => `  | ${JSON.stringify(j)}`).join('\n') : '  never')
  out.push('')
  out.push('export type RegionName =')
  const regions = Object.keys(manifest.regions.provided)
  out.push(regions.length ? regions.map((r) => `  | ${JSON.stringify(r)}`).join('\n') : '  never')
  out.push('')
  return out.join('\n')
}
