// Assembly only. Each concern lives in its own file so a reader looking for the
// models, the extension points or the server functions knows where to go without
// scrolling past the other two.

import { defineModule } from 'ketjs'
import { models } from './models.ts'
import { joints } from './joints.ts'
import { sections } from './sections.ts'
import { views } from './views.ts'
import { functions } from './functions.ts'
import { tokens } from './tokens.ts'
import { contentTypes, taxonomies } from './content-types.ts'
import { cmsFunctions } from './cms.ts'
import { jobs } from './jobs.ts'

export default defineModule({
  name: 'website',
  version: '0.1.0',
  app: true,
  title: 'Website',
  summary: 'Trang, section và điều hướng — nội dung soạn bằng dữ liệu, không phải code.',
  category: 'Website',
  messages: {
    vi: {
      'app.title': 'Website',
      'app.summary': 'Trang, section và điều hướng — nội dung soạn bằng dữ liệu, không phải code.',
      'app.category': 'Website',
      'page.notFound': 'Không tìm thấy trang',
      'content.page': 'Trang',
      'content.pages': 'Các trang',
      'content.post': 'Bài viết',
      'content.posts': 'Bài viết',
      'taxonomy.category': 'Chuyên mục',
      'taxonomy.categories': 'Chuyên mục',
      'taxonomy.tag': 'Thẻ',
      'taxonomy.tags': 'Thẻ',
      'error.forbidden': 'Bạn không có quyền thao tác trên website này.',
      'error.unknownField': 'Trường không được khai báo.',
      'error.required': 'Thông tin bắt buộc.',
      'error.invalidFieldType': 'Kiểu dữ liệu không hợp lệ.',
      'error.invalidTheme': 'Theme không có trong bản triển khai.',
      'error.invalidName': 'Tên không hợp lệ hoặc quá dài.',
      'error.invalidTitle': 'Tiêu đề không hợp lệ hoặc quá dài.',
      'error.invalidLocale': 'Mã ngôn ngữ không hợp lệ.',
      'error.payloadTooLarge': 'Dữ liệu vượt quá giới hạn cho phép.',
      'error.duplicateName': 'Tên này đã được sử dụng.',
      'error.duplicateHost': 'Tên miền này đã được gán cho website khác.',
      'error.duplicatePath': 'Đường dẫn này đã được sử dụng trên website.',
      'error.duplicateSlug': 'Slug này đã được sử dụng.',
      'error.siteNotFound': 'Không tìm thấy website.',
      'error.invalidHost': 'Tên miền không hợp lệ.',
      'error.invalidRole': 'Vai trò website không hợp lệ.',
      'error.immutableOwnership': 'Không thể chuyển dữ liệu sang website khác.',
      'error.editConflict': 'Nội dung đã thay đổi ở nơi khác. Hãy tải lại trước khi lưu.',
      'error.invalidContentType': 'Loại nội dung chưa được đăng ký.',
      'error.invalidPath': 'Đường dẫn nội bộ không hợp lệ.',
      'error.invalidSlug': 'Slug chỉ được chứa chữ, số và dấu gạch ngang.',
      'error.revisionNotFound': 'Không tìm thấy revision.',
      'error.invalidDatetime': 'Ngày giờ không hợp lệ.',
      'error.invalidTaxonomy': 'Taxonomy chưa được đăng ký.',
      'error.invalidParent': 'Term cha không hợp lệ.',
      'error.taxonomyCycle': 'Cấu trúc term tạo thành vòng lặp.',
      'error.termSiteMismatch': 'Nội dung và term phải thuộc cùng website.',
      'error.invalidDimensions': 'Kích thước media không hợp lệ.',
      'error.invalidRedirect': 'Hai đường dẫn redirect phải khác nhau và là đường dẫn nội bộ.',
      'error.redirectCycle': 'Redirect tạo thành vòng lặp.',
      'error.lastAdministrator': 'Website phải luôn còn ít nhất một quản trị viên.',
    },
    en: {
      'app.title': 'Website',
      'app.summary': 'Pages, sections and navigation — composed as data, not code.',
      'app.category': 'Website',
      'page.notFound': 'Page not found',
      'content.page': 'Page',
      'content.pages': 'Pages',
      'content.post': 'Post',
      'content.posts': 'Posts',
      'taxonomy.category': 'Category',
      'taxonomy.categories': 'Categories',
      'taxonomy.tag': 'Tag',
      'taxonomy.tags': 'Tags',
      'error.forbidden': 'You do not have access to this site.',
      'error.unknownField': 'This field is not declared.',
      'error.required': 'This field is required.',
      'error.invalidFieldType': 'The field has an invalid data type.',
      'error.invalidTheme': 'The theme is not shipped with this deployment.',
      'error.invalidName': 'The name is invalid or too long.',
      'error.invalidTitle': 'The title is invalid or too long.',
      'error.invalidLocale': 'The locale code is invalid.',
      'error.payloadTooLarge': 'The payload exceeds the allowed size.',
      'error.duplicateName': 'This name is already in use.',
      'error.duplicateHost': 'This domain is already assigned to another site.',
      'error.duplicatePath': 'This path is already in use on the site.',
      'error.duplicateSlug': 'This slug is already in use.',
      'error.siteNotFound': 'The site was not found.',
      'error.invalidHost': 'The domain name is invalid.',
      'error.invalidRole': 'The site role is invalid.',
      'error.immutableOwnership': 'This record cannot be moved to another site.',
      'error.editConflict': 'The content changed elsewhere. Reload it before saving.',
      'error.invalidContentType': 'The content type is not registered.',
      'error.invalidPath': 'The local path is invalid.',
      'error.invalidSlug': 'The slug may only contain letters, numbers and hyphens.',
      'error.revisionNotFound': 'The revision was not found.',
      'error.invalidDatetime': 'The date and time are invalid.',
      'error.invalidTaxonomy': 'The taxonomy is not registered.',
      'error.invalidParent': 'The parent term is invalid.',
      'error.taxonomyCycle': 'The term hierarchy contains a cycle.',
      'error.termSiteMismatch': 'The content and term must belong to the same site.',
      'error.invalidDimensions': 'The media dimensions are invalid.',
      'error.invalidRedirect': 'Redirect paths must be distinct local paths.',
      'error.redirectCycle': 'The redirect creates a cycle.',
      'error.lastAdministrator': 'A site must always retain at least one administrator.',
    },
  },
  requires: ['layout', 'website.page'],
  models,
  contentTypes,
  taxonomies,
  joints,
  sections,
  views,
  functions: { ...functions, ...cmsFunctions },
  jobs,
  tokens,
})

export type { SectionPlacement } from './types.ts'
