import type { ModelDef } from 'ketjs'

export const models: Record<string, ModelDef> = {
  Team: {
    scope: 'company',
    fields: {
      id: 'id',
      code: 'text',
      name: 'text',
      active: 'bool',
      leaderUserId: 'ref:user.User?',
      assignmentMode: 'text',
      assignmentCursor: 'int',
      version: 'int',
    },
    indexes: {
      code: { fields: ['companyId', 'code'], unique: true },
      active_name: { fields: ['companyId', 'active', 'name'] },
    },
  },
  TeamMember: {
    scope: 'company',
    fields: {
      id: 'id',
      teamId: 'ref:crm.Team',
      userId: 'ref:user.User',
      capacity: 'int',
      sequence: 'int',
      active: 'bool',
      assignedCount: 'int',
      lastAssignedAt: 'datetime?',
    },
    indexes: {
      identity: { fields: ['companyId', 'teamId', 'userId'], unique: true },
      routing: { fields: ['companyId', 'teamId', 'active', 'sequence'] },
    },
  },
  GamificationProfile: {
    scope: 'company',
    fields: {
      id: 'id',
      userId: 'ref:user.User',
      points: 'int',
      assigned: 'int',
      won: 'int',
      lost: 'int',
      activitiesDone: 'int',
      streak: 'int',
      refreshedAt: 'datetime',
    },
    indexes: {
      user: { fields: ['companyId', 'userId'], unique: true },
      leaderboard: { fields: ['companyId', 'points', 'userId'] },
    },
  },
  Stage: {
    scope: 'company',
    fields: {
      id: 'id',
      code: 'text',
      name: 'text',
      sequence: 'int',
      allowedKinds: 'json',
      terminalState: 'text',
      teamId: 'ref:crm.Team?',
      fold: 'bool',
      active: 'bool',
      version: 'int?',
    },
    indexes: {
      code: { fields: ['companyId', 'code'], unique: true },
      team_sequence: { fields: ['companyId', 'teamId', 'active', 'sequence'] },
    },
  },
  Tag: {
    scope: 'company',
    fields: { id: 'id', name: 'text', color: 'text?', active: 'bool' },
    indexes: { name: { fields: ['companyId', 'name'], unique: true } },
  },
  Case: {
    scope: 'company',
    fields: {
      id: 'id',
      kind: 'text',
      name: 'text',
      partnerId: 'ref:partner.Partner?',
      contactName: 'text?',
      email: 'text?',
      phone: 'text?',
      teamId: 'ref:crm.Team?',
      assigneeUserId: 'ref:user.User?',
      stageId: 'ref:crm.Stage',
      priority: 'text',
      description: 'text?',
      utmSource: 'text?',
      utmMedium: 'text?',
      utmCampaign: 'text?',
      terminalState: 'text',
      active: 'bool',
      version: 'int',
      score: 'decimal',
      mergedIntoId: 'ref:crm.Case?',
      threadId: 'ref:mail.Thread',
      createdByUserId: 'ref:user.User?',
      createdAt: 'datetime',
      updatedAt: 'datetime',
      convertedAt: 'datetime?',
      closedAt: 'datetime?',
    },
    indexes: {
      pipeline: { fields: ['companyId', 'kind', 'active', 'stageId', 'priority'] },
      assignee: { fields: ['companyId', 'assigneeUserId', 'active', 'updatedAt'] },
      partner: { fields: ['companyId', 'partnerId', 'active'] },
      email: { fields: ['companyId', 'email', 'active'] },
    },
  },
  CaseTag: {
    scope: 'company',
    fields: { id: 'id', caseId: 'ref:crm.Case', tagId: 'ref:crm.Tag' },
    indexes: { identity: { fields: ['companyId', 'caseId', 'tagId'], unique: true } },
  },
  SalesDetail: {
    scope: 'company',
    fields: {
      id: 'id',
      caseId: 'ref:crm.Case',
      expectedRevenue: 'decimal',
      recurringRevenue: 'decimal',
      probability: 'decimal',
      expectedClosing: 'date?',
      forecastCategory: 'text',
      lostReason: 'text?',
      sourceLeadId: 'ref:crm.Case?',
    },
    indexes: { case: { fields: ['companyId', 'caseId'], unique: true } },
  },
  TimelineEntry: {
    scope: 'company',
    fields: {
      id: 'id',
      caseId: 'ref:crm.Case',
      eventType: 'text',
      actorUserId: 'ref:user.User?',
      customerVisible: 'bool',
      body: 'text',
      metadata: 'json?',
      occurredAt: 'datetime',
    },
    indexes: { case_time: { fields: ['companyId', 'caseId', 'occurredAt'] } },
  },
  Message: {
    scope: 'company',
    fields: {
      id: 'id',
      caseId: 'ref:crm.Case',
      actorUserId: 'ref:user.User?',
      authorPartnerId: 'ref:partner.Partner?',
      visibility: 'text',
      body: 'text',
      createdAt: 'datetime',
    },
    indexes: { case_time: { fields: ['companyId', 'caseId', 'createdAt'] } },
  },
  ActivityLink: {
    scope: 'company',
    fields: { id: 'id', caseId: 'ref:crm.Case', activityId: 'ref:activity.Activity' },
    indexes: {
      activity: { fields: ['companyId', 'activityId'], unique: true },
      case: { fields: ['companyId', 'caseId'] },
    },
  },
  CalendarLink: {
    scope: 'company',
    fields: { id: 'id', caseId: 'ref:crm.Case', eventId: 'ref:calendar.Event' },
    indexes: {
      event: { fields: ['companyId', 'eventId'], unique: true },
      case: { fields: ['companyId', 'caseId'] },
    },
  },
  AssignmentRule: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      priority: 'int',
      allowedKinds: 'json',
      teamId: 'ref:crm.Team',
      assigneeUserId: 'ref:user.User?',
      utmSource: 'text?',
      minimumScore: 'decimal?',
      active: 'bool',
      version: 'int?',
    },
    indexes: { priority: { fields: ['companyId', 'active', 'priority'] } },
  },
  ScoreRule: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      field: 'text',
      operator: 'text',
      value: 'text',
      points: 'decimal',
      active: 'bool',
      sequence: 'int',
      version: 'int?',
    },
    indexes: { sequence: { fields: ['companyId', 'active', 'sequence'] } },
  },
  ScoreHistory: {
    scope: 'company',
    fields: { id: 'id', caseId: 'ref:crm.Case', score: 'decimal', reasons: 'json', calculatedAt: 'datetime' },
    indexes: { case_time: { fields: ['companyId', 'caseId', 'calculatedAt'] } },
  },
}
