import { defineModule } from 'ketjs'
import { contentTypes } from './content-types.ts'
import { functions } from './functions.ts'
import { models } from './models.ts'
import { sections } from './sections.ts'

export default defineModule({
  name: 'website_retail',
  version: '0.1.0',
  app: true,
  depends: ['website', 'product'],
  title: 'Website Retail',
  summary: 'Catalog, giỏ hàng và checkout lead cho website bán lẻ.',
  category: 'Website',
  messages: {
    vi: {
      'app.title': 'Website Retail',
      'app.summary': 'Catalog, giỏ hàng và checkout lead cho website bán lẻ.',
      'app.category': 'Website',
      'content.product': 'Sản phẩm website',
      'content.products': 'Sản phẩm website',
      'section.products': 'Lưới sản phẩm',
      'section.cart': 'Giỏ hàng',
      'error.invalidSite': 'Website không thuộc ngành retail hoặc đang tạm dừng.',
      'error.productUnavailable': 'Sản phẩm không khả dụng trên website này.',
      'error.duplicateProduct': 'Sản phẩm đã có trong catalog của website.',
      'error.invalidCurrency': 'Mã tiền tệ phải gồm ba chữ cái.',
      'error.cartUnavailable': 'Giỏ hàng không còn khả dụng.',
      'error.invalidQuantity': 'Số lượng phải lớn hơn 0 và không vượt quá 10.000.',
      'error.cartConflict': 'Giỏ hàng vừa thay đổi. Vui lòng thử lại.',
      'error.emptyCart': 'Giỏ hàng đang trống.',
      'error.invalidName': 'Tên khách hàng không hợp lệ hoặc quá dài.',
      'error.invalidEmail': 'Địa chỉ email không hợp lệ.',
      'error.invalidPhone': 'Số điện thoại không hợp lệ.',
      'error.noteTooLong': 'Ghi chú vượt quá giới hạn cho phép.',
    },
    en: {
      'app.title': 'Retail website',
      'app.summary': 'Catalogue, cart and checkout leads for retail sites.',
      'app.category': 'Website',
      'content.product': 'Website product',
      'content.products': 'Website products',
      'section.products': 'Product grid',
      'section.cart': 'Cart',
      'error.invalidSite': 'The site is not an active retail site.',
      'error.productUnavailable': 'The product is not available on this site.',
      'error.duplicateProduct': 'The product is already in this site catalog.',
      'error.invalidCurrency': 'The currency code must contain three letters.',
      'error.cartUnavailable': 'The cart is no longer available.',
      'error.invalidQuantity': 'Quantity must be positive and no greater than 10,000.',
      'error.cartConflict': 'The cart changed concurrently. Please retry.',
      'error.emptyCart': 'The cart is empty.',
      'error.invalidName': 'The customer name is invalid or too long.',
      'error.invalidEmail': 'The email address is invalid.',
      'error.invalidPhone': 'The phone number is invalid.',
      'error.noteTooLong': 'The note exceeds the allowed length.',
    },
  },
  models,
  functions,
  contentTypes,
  sections,
})
