import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Sequence: { scope: 'company', fields: { id: 'id', nextNumber: 'int' } },
  SessionLock: { scope: 'company', fields: { id: 'id', sessionId: 'text' } },
  Config: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      warehouseId: 'ref:stock.Warehouse',
      pricelistId: 'ref:pricing.Pricelist?',
      salesJournalId: 'ref:account.Journal',
      revenueAccountId: 'ref:account.Account',
      receivableAccountId: 'ref:account.Account',
      taxAccountId: 'ref:account.Account?',
      cashOverShortAccountId: 'ref:account.Account?',
      cashRoundingIncrement: 'decimal',
      maximumDifference: 'decimal',
      active: 'bool',
    },
  },
  PaymentMethod: {
    scope: 'company',
    fields: { id: 'id', name: 'text', journalId: 'ref:account.Journal', isCash: 'bool', active: 'bool' },
  },
  ConfigPaymentMethod: {
    scope: 'company',
    fields: { id: 'id', configId: 'ref:pos.Config', paymentMethodId: 'ref:pos.PaymentMethod' },
    indexes: { config_method: { fields: ['companyId', 'configId', 'paymentMethodId'], unique: true } },
  },
  Session: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      configId: 'ref:pos.Config',
      userId: 'ref:user.User',
      deviceId: 'text?',
      state: 'text',
      startAt: 'datetime?',
      stopAt: 'datetime?',
      openingNotes: 'text?',
      closingNotes: 'text?',
      cashRegisterBalanceStart: 'decimal',
      cashRegisterBalanceEnd: 'decimal',
      cashRegisterBalanceEndReal: 'decimal',
      cashRegisterDifference: 'decimal',
      varianceStatus: 'text',
      varianceReason: 'text?',
      varianceNote: 'text?',
      varianceApprovedBy: 'text?',
      varianceApprovedAt: 'datetime?',
      cashAdjustmentId: 'ref:pos.CashAdjustment?',
      revision: 'int?',
    },
    indexes: { config_state: { fields: ['companyId', 'configId', 'state'] } },
  },
  Exchange: {
    scope: 'company',
    fields: {
      id: 'id',
      uuid: 'text',
      originalOrderId: 'ref:pos.Order',
      returnOrderId: 'ref:pos.Order',
      replacementOrderId: 'ref:pos.Order',
      originalRevision: 'int',
      reason: 'text?',
      createdAt: 'datetime',
    },
    indexes: {
      company_uuid: { fields: ['companyId', 'uuid'], unique: true },
      return_order: { fields: ['companyId', 'returnOrderId'], unique: true },
      replacement_order: { fields: ['companyId', 'replacementOrderId'], unique: true },
    },
  },
  Order: {
    scope: 'company',
    fields: {
      id: 'id',
      uuid: 'text',
      name: 'text',
      posReference: 'text',
      sequenceNumber: 'int',
      sessionId: 'ref:pos.Session',
      configId: 'ref:pos.Config',
      partnerId: 'ref:partner.Partner?',
      state: 'text',
      invoiceStatus: 'text',
      isRefund: 'bool',
      refundedOrderId: 'ref:pos.Order?',
      returnPortion: 'decimal?',
      returnComplete: 'bool?',
      exchangeId: 'ref:pos.Exchange?',
      exchangeRole: 'text?',
      dateOrder: 'datetime',
      currency: 'text',
      amountUntaxed: 'decimal',
      amountTax: 'decimal',
      amountExact: 'decimal',
      amountRounding: 'decimal',
      amountTotal: 'decimal',
      amountPaid: 'decimal',
      amountReturn: 'decimal',
      toInvoice: 'bool',
      accountMoveId: 'ref:account.Move?',
      pickingId: 'ref:stock.Picking?',
      note: 'text?',
      revision: 'int?',
      operatorId: 'text?',
      deviceId: 'text?',
      priceBookRevision: 'text?',
    },
    indexes: {
      company_uuid: { fields: ['companyId', 'uuid'], unique: true },
      session_sequence: { fields: ['companyId', 'sessionId', 'sequenceNumber'], unique: true },
      exchange_role: { fields: ['companyId', 'exchangeId', 'exchangeRole'], unique: true },
    },
  },
  OrderLine: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      productId: 'ref:product.Product',
      productUomId: 'ref:uom.Unit',
      name: 'text',
      qty: 'decimal',
      priceUnit: 'decimal',
      discount: 'decimal',
      taxId: 'ref:account.Tax?',
      taxIds: 'json?',
      taxEvidence: 'json?',
      quoteRevision: 'text?',
      tracking: 'text?',
      lotSelections: 'json?',
      affectsStock: 'bool?',
      overrideReason: 'text?',
      overrideBy: 'text?',
      priceSubtotal: 'decimal',
      priceSubtotalIncl: 'decimal',
      refundedOrderlineId: 'ref:pos.OrderLine?',
      sequence: 'int',
    },
  },
  Payment: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      paymentMethodId: 'ref:pos.PaymentMethod',
      amount: 'decimal',
      tenderedAmount: 'decimal',
      appliedAmount: 'decimal',
      state: 'text',
      kind: 'text',
      reference: 'text?',
      operatorId: 'text?',
      deviceId: 'text?',
      paymentDate: 'datetime',
    },
  },
  CashAdjustment: {
    scope: 'company',
    fields: {
      id: 'id',
      sessionId: 'ref:pos.Session',
      amount: 'decimal',
      reason: 'text',
      note: 'text?',
      approvedBy: 'text',
      approvedAt: 'datetime',
      accountMoveId: 'ref:account.Move',
    },
    indexes: { session: { fields: ['companyId', 'sessionId'], unique: true } },
  },
  CashMovement: {
    scope: 'company',
    fields: {
      id: 'id',
      sessionId: 'ref:pos.Session',
      direction: 'text',
      amount: 'decimal',
      reason: 'text',
      note: 'text?',
      actorId: 'text',
      deviceId: 'text?',
      occurredAt: 'datetime',
      reversalOfId: 'ref:pos.CashMovement?',
    },
    indexes: { session_time: { fields: ['companyId', 'sessionId', 'occurredAt'] } },
  },
}
