import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Sequence: { scope: 'company', fields: { id: 'id', nextNumber: 'int' } },
  Config: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      warehouseId: 'ref:stock.Warehouse',
      pricelistId: 'ref:pricing.Pricelist?',
      salesJournalId: 'ref:account.Journal',
      revenueAccountId: 'ref:account.Account',
      receivableAccountId: 'ref:account.Account',
      taxAccountId: 'ref:account.Account?',
      maximumDifference: 'decimal',
      active: 'bool',
    },
  },
  PaymentMethod: {
    scope: 'company',
    fields: { id: 'id', name: 'text', journalId: 'ref:account.Journal', isCash: 'bool', active: 'bool' },
  },
  ConfigPaymentMethod: {
    scope: 'company',
    fields: { id: 'id', configId: 'ref:pos.Config', paymentMethodId: 'ref:pos.PaymentMethod' },
    indexes: { config_method: { fields: ['companyId', 'configId', 'paymentMethodId'], unique: true } },
  },
  Session: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      configId: 'ref:pos.Config',
      userId: 'ref:user.User',
      state: 'text',
      startAt: 'datetime?',
      stopAt: 'datetime?',
      openingNotes: 'text?',
      closingNotes: 'text?',
      cashRegisterBalanceStart: 'decimal',
      cashRegisterBalanceEnd: 'decimal',
      cashRegisterBalanceEndReal: 'decimal',
      cashRegisterDifference: 'decimal',
    },
    indexes: { config_state: { fields: ['companyId', 'configId', 'state'] } },
  },
  Order: {
    scope: 'company',
    fields: {
      id: 'id',
      uuid: 'text',
      name: 'text',
      posReference: 'text',
      sequenceNumber: 'int',
      sessionId: 'ref:pos.Session',
      configId: 'ref:pos.Config',
      partnerId: 'ref:partner.Partner?',
      state: 'text',
      invoiceStatus: 'text',
      isRefund: 'bool',
      refundedOrderId: 'ref:pos.Order?',
      dateOrder: 'datetime',
      currency: 'text',
      amountUntaxed: 'decimal',
      amountTax: 'decimal',
      amountTotal: 'decimal',
      amountPaid: 'decimal',
      amountReturn: 'decimal',
      toInvoice: 'bool',
      accountMoveId: 'ref:account.Move?',
      pickingId: 'ref:stock.Picking?',
      note: 'text?',
    },
    indexes: {
      company_uuid: { fields: ['companyId', 'uuid'], unique: true },
      session_sequence: { fields: ['companyId', 'sessionId', 'sequenceNumber'], unique: true },
    },
  },
  OrderLine: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      productId: 'ref:product.Product',
      productUomId: 'ref:uom.Unit',
      name: 'text',
      qty: 'decimal',
      priceUnit: 'decimal',
      discount: 'decimal',
      taxId: 'ref:account.Tax?',
      taxIds: 'json?',
      taxEvidence: 'json?',
      quoteRevision: 'text?',
      priceSubtotal: 'decimal',
      priceSubtotalIncl: 'decimal',
      refundedOrderlineId: 'ref:pos.OrderLine?',
      sequence: 'int',
    },
  },
  Payment: {
    scope: 'company',
    fields: {
      id: 'id',
      orderId: 'ref:pos.Order',
      paymentMethodId: 'ref:pos.PaymentMethod',
      amount: 'decimal',
      paymentDate: 'datetime',
    },
  },
}
