import { defineModule } from '@ketvietlab/ketjs'
import { analyticsFunctions } from './analytics.ts'
import { functions } from './functions.ts'
import { models } from './models.ts'
import { relations } from './relations.ts'
import { reportFunctions, reports } from './reports.ts'

export default defineModule({
  name: 'account',
  // 0.9.0 establishes the Wave 0 ledger contract: exact-money arithmetic,
  // immutable company-civil dates, shared draft validation and resumable writes.
  // 0.8.0 adds ledger analytics — performance, position, revenueTimeline,
  // openItemSummary and cashFlow, the aggregates an overview screen is made of.
  // 0.7.0 adds a company-scoped product-to-sales-tax mapping. Products remain
  // shared catalogue data while the tax belongs to one legal entity's chart.
  version: '0.9.0',
  depends: ['company', 'partner', 'product', 'uom'],
  title: 'Kế toán',
  summary: 'Sổ cái, hoá đơn, thanh toán và hệ thống tài khoản Việt Nam theo TT99.',
  category: 'Tài chính',
  models,
  relations,
  functions: { ...functions, ...reportFunctions, ...analyticsFunctions },
  reports,
  messages: {
    vi: {
      'app.title': 'Kế toán',
      'app.summary': 'Sổ cái, hoá đơn, thanh toán và hệ thống tài khoản Việt Nam theo TT99.',
      'app.category': 'Tài chính',
      'report.customerInvoice': 'HÓA ĐƠN KHÁCH HÀNG',
      'report.vendorBill': 'HÓA ĐƠN NHÀ CUNG CẤP',
      'report.number': 'Số',
      'report.date': 'Ngày',
      'report.partner': 'Đối tác',
      'report.description': 'Mô tả',
      'report.quantity': 'Số lượng',
      'report.unitPrice': 'Đơn giá',
      'report.balance': 'Giá trị',
      'report.untaxed': 'Trước thuế',
      'report.tax': 'Thuế',
      'report.total': 'Tổng cộng',

      'error.moveMissing': 'Bút toán không tồn tại.',
      'error.moveDraftOnly': 'Chỉ bút toán ở trạng thái nháp mới ghi sổ được.',
      'error.movePostedOnly': 'Chỉ bút toán đã ghi sổ mới đảo được.',
      'error.moveNotCancellable': 'Bút toán đã ghi sổ được sửa bằng cách đảo, không huỷ trực tiếp.',
      'error.moveConcurrent': 'Bút toán vừa thay đổi; hãy kiểm tra lại rồi thử lại.',
      'error.moveIdReused': 'Mã này đã thuộc về một bút toán khác.',
      'error.moveTypeUnsupported': 'Loại chứng từ không được hỗ trợ.',
      'error.linesTooFew': 'Một bút toán cần ít nhất hai dòng.',
      'error.lineSideBoth': 'Mỗi dòng chỉ ghi Nợ hoặc Có, không âm và không ghi cả hai.',
      'error.lineAmountRequired': 'Mỗi dòng bút toán phải có số tiền Nợ hoặc Có khác 0.',
      'error.lineBalanceInvalid': 'Số dư dòng phải bằng số Nợ trừ số Có.',
      'error.lineResidualInvalid': 'Số dư còn lại của dòng không khớp với tài khoản và số tiền.',
      'error.entryUnbalanced': 'Bút toán chưa cân đối: Nợ {debit}, Có {credit}.',
      'error.moveTotalInvalid': 'Tổng chứng từ không khớp với các dòng bút toán đã cân đối.',
      'error.reversalNoLines': 'Bút toán không có dòng nào để đảo.',
      'error.reversalIdReused': 'Mã này đã thuộc về một bút toán đảo khác.',
      'error.moveAlreadyReversed': 'Bút toán này đã có một bút toán đảo khác.',
      'error.lineDraftOnly': 'Chỉ thêm được dòng vào bút toán còn ở trạng thái nháp.',
      'error.lineIdTaken': 'Mã này đã thuộc về một dòng bút toán khác.',
      'error.moneyExactString':
        'Giá trị tiền phải là chuỗi số thập phân chính xác, không dùng số JavaScript hoặc ký hiệu số mũ.',
      'error.accountingDateInvalid': 'Ngày hạch toán và ngày chứng từ phải là ngày dân sự hợp lệ.',
      'error.moveCurrencyMismatch': 'Tiền tệ bút toán phải khớp với sổ cái của công ty đang chọn.',

      'error.accountMissing': 'Tài khoản không tồn tại.',
      'error.accountInactive': 'Không thể ghi dòng bút toán mới vào tài khoản đã ngưng sử dụng.',
      'error.accountTypeUnsupported': 'Loại tài khoản không được hỗ trợ.',
      'error.accountCodeFormat': 'Mã tài khoản chỉ gồm chữ, số và dấu chấm.',
      'error.offBalanceReconcile': 'Tài khoản ngoài bảng không đối soát được.',
      'error.defaultAccountMissing': 'Tài khoản mặc định không tồn tại.',

      'error.journalMissing': 'Sổ nhật ký không tồn tại.',
      'error.journalInactive': 'Không thể ghi bút toán mới vào sổ nhật ký đã ngưng sử dụng.',
      'error.journalTypeUnsupported': 'Loại sổ nhật ký không được hỗ trợ.',
      'error.journalCodeFormat': 'Mã sổ nhật ký chỉ gồm chữ và số.',
      'error.journalMustBeSale': 'Chứng từ khách hàng phải ghi vào sổ bán hàng.',
      'error.journalMustBePurchase': 'Chứng từ nhà cung cấp phải ghi vào sổ mua hàng.',
      'error.journalLiquidityMissing': 'Sổ nhật ký thanh toán cần một tài khoản tiền mặc định.',
      'error.journalNotLiquidity': 'Thanh toán phải dùng sổ ngân hàng hoặc tiền mặt.',

      'error.taxMissing': 'Sắc thuế không tồn tại.',
      'error.taxUseUnsupported': 'Phạm vi sử dụng thuế không được hỗ trợ.',
      'error.taxComputationUnsupported': 'Cách tính thuế không được hỗ trợ.',
      'error.taxScopeUnsupported': 'Phạm vi hàng hoá phải là dịch vụ hoặc hàng hoá.',
      'error.taxAccountMissing': 'Tài khoản thuế không tồn tại.',
      'error.taxDirectionMismatch': 'Thuế “{name}” không khớp chiều của chứng từ.',
      'error.taxPostingAccountMissing': 'Thuế “{name}” cần một tài khoản hạch toán hợp lệ.',
      'error.taxMixedPriceInclude':
        'Một dòng không thể vừa có thuế đã gồm trong giá vừa có thuế chưa gồm trong giá.',
      'error.taxManyPriceInclude': 'Mỗi dòng chỉ chịu tối đa một sắc thuế đã gồm trong giá.',
      'error.taxDivisionFull': 'Thuế tính ngược từ 100% trở lên không có cơ sở tính hữu hạn.',
      'error.productMissing': 'Mẫu sản phẩm không tồn tại.',

      'error.partnerMissing': 'Đối tác không tồn tại.',
      'error.paymentTermMissing': 'Điều khoản thanh toán không tồn tại.',
      'error.termValueUnsupported': 'Kiểu giá trị phải là phần trăm hoặc số tiền cố định.',
      'error.termDelayUnsupported': 'Cách tính hạn không được hỗ trợ.',
      'error.termPercentRange': 'Phần trăm phải nằm trong khoảng 0 đến 100.',

      'error.invoiceTypeRequired':
        'Chức năng này cần loại chứng từ là hoá đơn, hoá đơn trả lại hoặc biên lai.',
      'error.invoiceIdReused': 'Mã này đã thuộc về một hoá đơn khác.',
      'error.invoiceAccountsMissing': 'Tài khoản trên hoá đơn không tồn tại.',
      'error.lineAccountUndecided':
        'Chưa chọn tài khoản doanh thu/chi phí, mà nhóm sản phẩm lẫn công ty đều chưa đặt mặc định.',
      'error.counterpartAccountUndecided':
        'Chưa chọn tài khoản phải thu/phải trả, mà đối tác lẫn công ty đều chưa đặt mặc định.',
      'error.categoryMissing': 'Nhóm sản phẩm không tồn tại.',
      'error.defaultAccountType': 'Loại tài khoản này không dùng làm mặc định cho mục đích đó được.',
      'error.counterpartMustBeReceivable': 'Tài khoản đối ứng phải là tài khoản phải thu.',
      'error.counterpartMustBePayable': 'Tài khoản đối ứng phải là tài khoản phải trả.',

      'error.paymentTypeUnsupported': 'Loại thanh toán phải là nhận tiền hoặc gửi tiền.',
      'error.partnerTypeUnsupported': 'Loại đối tác phải là khách hàng hoặc nhà cung cấp.',
      'error.amountPositive': 'Số tiền thanh toán phải lớn hơn 0.',
      'error.destinationMissing': 'Tài khoản đối ứng không tồn tại.',
      'error.destinationMustBeReceivable': 'Thu tiền khách hàng phải tất toán một tài khoản phải thu.',
      'error.destinationMustBePayable': 'Chi trả nhà cung cấp phải tất toán một tài khoản phải trả.',
      'error.openItemMissing': 'Khoản công nợ đang mở không tồn tại.',
      'error.openItemAccountMismatch': 'Khoản công nợ này thuộc một tài khoản đối ứng khác.',
      'error.openItemDirection': 'Khoản công nợ này ngược chiều Nợ/Có với thanh toán.',
      'error.amountExceedsOpenItem': 'Số tiền thanh toán vượt quá khoản công nợ đã chọn.',

      'error.reconcileAmountPositive': 'Số tiền đối soát phải lớn hơn 0.',
      'error.reconcileSides': 'Đối soát cần một dòng Nợ và một dòng Có.',
      'error.reconcileAccountMismatch': 'Hai dòng đối soát phải cùng một tài khoản.',
      'error.reconcilePostedOnly': 'Chỉ đối soát được các dòng đã ghi sổ.',
      'error.reconcileNotAllowed': 'Tài khoản này không cho phép đối soát.',
      'error.reconcileAmountExceeds': 'Số tiền vượt quá số dư còn lại.',
      'error.reconcileConcurrent': 'Số dư còn lại vừa thay đổi; hãy đối soát lại.',
    },
    en: {
      'app.title': 'Accounting',
      'app.summary': 'Ledger, invoices, payments, and Vietnam accounting defaults under Circular 99.',
      'app.category': 'Finance',
      'report.customerInvoice': 'CUSTOMER INVOICE',
      'report.vendorBill': 'VENDOR BILL',
      'report.number': 'Number',
      'report.date': 'Date',
      'report.partner': 'Partner',
      'report.description': 'Description',
      'report.quantity': 'Quantity',
      'report.unitPrice': 'Unit price',
      'report.balance': 'Amount',
      'report.untaxed': 'Untaxed',
      'report.tax': 'Tax',
      'report.total': 'Total',

      'error.moveMissing': 'The journal entry does not exist.',
      'error.moveDraftOnly': 'Only a draft entry can be posted.',
      'error.movePostedOnly': 'Only a posted entry can be reversed.',
      'error.moveNotCancellable': 'A posted entry is corrected by reversing it, not by cancelling it.',
      'error.moveConcurrent': 'The journal entry changed; review it and try again.',
      'error.moveIdReused': 'A different journal entry already uses this id.',
      'error.moveTypeUnsupported': 'That document type is not supported.',
      'error.linesTooFew': 'A journal entry needs at least two lines.',
      'error.lineSideBoth': 'Each line takes a debit or a credit, never both, and never a negative amount.',
      'error.lineAmountRequired': 'Each journal item needs a non-zero debit or credit.',
      'error.lineBalanceInvalid': 'A journal item balance must equal debit minus credit.',
      'error.lineResidualInvalid': 'A journal item residual does not match its account and balance.',
      'error.entryUnbalanced': 'The entry is not balanced: debit {debit}, credit {credit}.',
      'error.moveTotalInvalid': 'The document totals do not match its balanced journal items.',
      'error.reversalNoLines': 'The entry has no journal items to reverse.',
      'error.reversalIdReused': 'A different reversal already uses this id.',
      'error.moveAlreadyReversed': 'This entry already has a different reversal.',
      'error.lineDraftOnly': 'Lines can only be added to an entry that is still a draft.',
      'error.lineIdTaken': 'A different journal item already uses this id.',
      'error.moneyExactString':
        'A money value must be an exact decimal string, not a JavaScript number or exponent notation.',
      'error.accountingDateInvalid': 'Accounting and document dates must be valid civil dates.',
      'error.moveCurrencyMismatch': 'The journal entry currency must match the active company ledger.',

      'error.accountMissing': 'The account does not exist.',
      'error.accountInactive': 'An inactive account cannot receive a new journal item.',
      'error.accountTypeUnsupported': 'That account type is not supported.',
      'error.accountCodeFormat': 'An account code may contain only letters, numbers, and dots.',
      'error.offBalanceReconcile': 'An off-balance account cannot be reconciled.',
      'error.defaultAccountMissing': 'The default account does not exist.',

      'error.journalMissing': 'The journal does not exist.',
      'error.journalInactive': 'An inactive journal cannot post a new entry.',
      'error.journalTypeUnsupported': 'That journal type is not supported.',
      'error.journalCodeFormat': 'A journal code must be alphanumeric.',
      'error.journalMustBeSale': 'A customer document belongs in a sale journal.',
      'error.journalMustBePurchase': 'A vendor document belongs in a purchase journal.',
      'error.journalLiquidityMissing': 'A payment journal needs a default liquidity account.',
      'error.journalNotLiquidity': 'Payments require a bank or cash journal.',

      'error.taxMissing': 'The tax does not exist.',
      'error.taxUseUnsupported': 'That tax use is not supported.',
      'error.taxComputationUnsupported': 'That tax computation is not supported.',
      'error.taxScopeUnsupported': 'A tax scope must be service or goods.',
      'error.taxAccountMissing': 'The tax account does not exist.',
      'error.taxDirectionMismatch': 'Tax “{name}” does not match the direction of this document.',
      'error.taxPostingAccountMissing': 'Tax “{name}” needs a valid posting account.',
      'error.taxMixedPriceInclude': 'A line cannot mix price-included and price-excluded taxes.',
      'error.taxManyPriceInclude': 'A line carries at most one price-included tax.',
      'error.taxDivisionFull': 'A division tax of 100% or more has no finite base.',
      'error.productMissing': 'The product template does not exist.',

      'error.partnerMissing': 'The partner does not exist.',
      'error.paymentTermMissing': 'The payment term does not exist.',
      'error.termValueUnsupported': 'A value type must be a percentage or a fixed amount.',
      'error.termDelayUnsupported': 'That due-date rule is not supported.',
      'error.termPercentRange': 'A percentage must be between 0 and 100.',

      'error.invoiceTypeRequired': 'This needs an invoice, refund, or receipt document type.',
      'error.invoiceIdReused': 'A different invoice already uses this id.',
      'error.invoiceAccountsMissing': 'The accounts on this invoice do not exist.',
      'error.lineAccountUndecided':
        'No revenue or expense account was given, and neither the product category nor the company has a default.',
      'error.counterpartAccountUndecided':
        'No receivable or payable account was given, and neither the partner nor the company has a default.',
      'error.categoryMissing': 'The product category does not exist.',
      'error.defaultAccountType': 'That account type cannot serve as this default.',
      'error.counterpartMustBeReceivable': 'The counterpart account must be a receivable account.',
      'error.counterpartMustBePayable': 'The counterpart account must be a payable account.',

      'error.paymentTypeUnsupported': 'A payment must be inbound or outbound.',
      'error.partnerTypeUnsupported': 'A partner type must be customer or supplier.',
      'error.amountPositive': 'The payment amount must be greater than zero.',
      'error.destinationMissing': 'The destination account does not exist.',
      'error.destinationMustBeReceivable': 'Money received from a customer settles a receivable account.',
      'error.destinationMustBePayable': 'Money paid to a supplier settles a payable account.',
      'error.openItemMissing': 'The open item does not exist.',
      'error.openItemAccountMismatch': 'That open item belongs to another destination account.',
      'error.openItemDirection': 'That open item runs the opposite way to this payment.',
      'error.amountExceedsOpenItem': 'The payment amount exceeds the open item it was matched to.',

      'error.reconcileAmountPositive': 'A reconciliation amount must be greater than zero.',
      'error.reconcileSides': 'Reconciliation needs one debit line and one credit line.',
      'error.reconcileAccountMismatch': 'Reconciled lines must use the same account.',
      'error.reconcilePostedOnly': 'Only posted journal items can be reconciled.',
      'error.reconcileNotAllowed': 'This account does not allow reconciliation.',
      'error.reconcileAmountExceeds': 'The amount exceeds a residual balance.',
      'error.reconcileConcurrent': 'The residual balance changed just now; reconcile again.',
    },
  },
})

export {
  ACCOUNT_TYPES,
  JOURNAL_TYPES,
  MOVE_TYPES,
  MOVE_STATES,
  PAYMENT_STATES,
  PAYMENT_TYPES,
  PARTNER_TYPES,
  PAYMENT_TERM_VALUES,
  PAYMENT_TERM_DELAY_TYPES,
  TAX_USES,
  TAX_AMOUNT_TYPES,
} from './functions.ts'
export {
  TT99_ACCOUNTS,
  TT99_ACCOUNT_CHECKSUM,
  TT99_CATALOG_CHECKSUM,
  TT99_CODE,
  VIETNAM_TAXES,
} from './tt99.ts'
