import type { ModelDef } from '@ketvietlab/ketjs'

export const models: Record<string, ModelDef> = {
  Setup: {
    scope: 'company',
    fields: {
      id: 'id',
      countryCode: 'text',
      standard: 'text',
      legalBasis: 'text',
      sourceChecksum: 'text',
      installedAt: 'datetime',
    },
    indexes: { company: { fields: ['companyId'], unique: true } },
  },
  Account: {
    scope: 'company',
    fields: {
      id: 'id',
      code: 'text',
      name: 'text',
      accountType: 'text',
      reconcile: 'bool',
      active: 'bool',
    },
    indexes: { company_code: { fields: ['companyId', 'code'], unique: true } },
  },
  Journal: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      code: 'text',
      type: 'text',
      defaultAccountId: 'ref:account.Account?',
      sequenceNumber: 'int',
      active: 'bool',
    },
    indexes: { company_code: { fields: ['companyId', 'code'], unique: true } },
  },
  Tax: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      description: 'text?',
      typeTaxUse: 'text',
      taxScope: 'text?',
      amountType: 'text',
      amount: 'decimal',
      priceInclude: 'bool',
      includeBaseAmount: 'bool',
      accountId: 'ref:account.Account?',
      sequence: 'int',
      active: 'bool',
    },
  },
  PaymentTerm: {
    scope: 'company',
    fields: { id: 'id', name: 'text', note: 'text?', active: 'bool' },
  },
  PaymentTermLine: {
    scope: 'company',
    fields: {
      id: 'id',
      paymentId: 'ref:account.PaymentTerm',
      value: 'text',
      valueAmount: 'decimal',
      delayType: 'text',
      nbDays: 'int',
      daysNextMonth: 'int?',
      sequence: 'int',
    },
  },
  Move: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      ref: 'text?',
      date: 'datetime',
      moveType: 'text',
      state: 'text',
      journalId: 'ref:account.Journal',
      partnerId: 'ref:partner.Partner?',
      invoiceDate: 'datetime?',
      invoiceDateDue: 'datetime?',
      paymentTermId: 'ref:account.PaymentTerm?',
      paymentState: 'text',
      currency: 'text',
      amountUntaxed: 'decimal',
      amountTax: 'decimal',
      amountTotal: 'decimal',
      postedAt: 'datetime?',
    },
    indexes: { journal_name: { fields: ['companyId', 'journalId', 'name'], unique: true } },
  },
  MoveLine: {
    scope: 'company',
    fields: {
      id: 'id',
      moveId: 'ref:account.Move',
      name: 'text',
      accountId: 'ref:account.Account',
      partnerId: 'ref:partner.Partner?',
      productId: 'ref:product.Product?',
      productUomId: 'ref:uom.Unit?',
      quantity: 'decimal',
      priceUnit: 'decimal',
      discount: 'decimal',
      taxId: 'ref:account.Tax?',
      debit: 'decimal',
      credit: 'decimal',
      balance: 'decimal',
      dateMaturity: 'datetime?',
      displayType: 'text?',
      reconciled: 'bool',
      amountResidual: 'decimal',
      sequence: 'int',
    },
  },
  PartialReconcile: {
    scope: 'company',
    fields: {
      id: 'id',
      debitMoveId: 'ref:account.MoveLine',
      creditMoveId: 'ref:account.MoveLine',
      amount: 'decimal',
      date: 'datetime',
    },
    indexes: { pair: { fields: ['companyId', 'debitMoveId', 'creditMoveId'] } },
  },
  Payment: {
    scope: 'company',
    fields: {
      id: 'id',
      name: 'text',
      paymentType: 'text',
      partnerType: 'text',
      partnerId: 'ref:partner.Partner?',
      journalId: 'ref:account.Journal',
      destinationAccountId: 'ref:account.Account',
      amount: 'decimal',
      date: 'datetime',
      memo: 'text?',
      paymentReference: 'text?',
      state: 'text',
      currency: 'text',
      moveId: 'ref:account.Move?',
    },
  },
}
