import { defineModule } from '@ketvietlab/ketjs'
import { routes } from './routes.ts'

export default defineModule({
  name: 'attendance_backend',
  version: '0.1.0',
  depends: ['attendance', 'hr_backend', 'backend'],
  title: 'Chấm công trong quản trị',
  summary: 'Kiosk, self-service và chốt kỳ công.',
  category: 'Nhân sự',
  routes,
  menus: {
    attendance: {
      label: 'menu.app',
      icon: 'calendar',
      path: '/admin/attendance',
      sequence: 41,
      needs: 'attendance.period.report',
    },
    'attendance.credentials': {
      parent: 'attendance',
      label: 'menu.credentials',
      path: '/admin/attendance/credentials',
      sequence: 10,
      needs: 'attendance.credential.managePin',
    },
    'attendance.mine': {
      label: 'menu.mine',
      icon: 'check-circle',
      path: '/my/work',
      sequence: 42,
      needs: 'attendance.punch.self',
    },
  },
  messages: {
    vi: {
      'app.title': 'Chấm công trong quản trị',
      'app.summary': 'Kiosk, self-service và chốt kỳ công.',
      'app.category': 'Nhân sự',
      'menu.app': 'Chấm công',
      'menu.credentials': 'Kiosk và mã chấm công',
      'menu.mine': 'Công việc của tôi',
      'my.title': 'Công việc của tôi',
      'my.profile': 'Hồ sơ',
      'my.schedule': 'Lịch ca',
      'my.sessions': 'Lịch sử chấm công',
      'my.leave': 'Nghỉ phép',
      'admin.title': 'Bảng công tháng',
      'kiosk.title': 'Kiosk chấm công',
      'kiosk.hint': 'Nhập mã nhân viên và PIN, hoặc quét QR vào ô QR.',
      'credentials.title': 'Kiosk và mã chấm công',
      'credentials.kiosk': 'Cấp kiosk',
      'credentials.pin': 'Đặt PIN',
      'credentials.qr': 'Cấp lại QR',
      'credentials.once': 'Secret chỉ hiển thị một lần',
      'period.state': 'Trạng thái kỳ',
      'period.reopenReason': 'Điều chỉnh kỳ công đã khóa',
      'result.title': 'Kết quả',
      'result.success': 'Thành công',
      'result.failed': 'Không thể hoàn tất',
      'punch.in': 'Đã ghi nhận vào ca',
      'punch.out': 'Đã ghi nhận ra ca',
      'field.employee': 'Nhân viên',
      'field.employeeCode': 'Mã nhân viên',
      'field.branch': 'Chi nhánh',
      'field.date': 'Ngày',
      'field.start': 'Vào',
      'field.stop': 'Ra',
      'field.state': 'Trạng thái',
      'field.leaveType': 'Loại phép',
      'field.dateFrom': 'Từ ngày',
      'field.dateTo': 'Đến ngày',
      'field.portion': 'Buổi',
      'field.reason': 'Lý do',
      'field.pin': 'PIN',
      'field.qr': 'QR token',
      'field.name': 'Tên',
      'field.month': 'Tháng',
      'field.planned': 'Kế hoạch',
      'field.worked': 'Thực tế',
      'field.overtime': 'Tăng ca duyệt',
      'field.exception': 'Ngoại lệ',
      'portion.full': 'Cả ngày',
      'portion.morning': 'Buổi sáng',
      'portion.afternoon': 'Buổi chiều',
      'action.punch': 'Chấm công',
      'action.requestLeave': 'Gửi yêu cầu',
      'action.openPeriod': 'Mở kỳ',
      'action.close': 'Chốt kỳ',
      'action.reopen': 'Mở lại',
      'action.issue': 'Cấp kiosk',
      'action.savePin': 'Lưu PIN',
      'action.issueQr': 'Cấp QR',
      'state.open': 'Đang mở',
      'state.closed': 'Đã kết thúc',
      'state.locked': 'Đã khóa',
      'empty.profile': 'Chưa liên kết nhân viên',
      'empty.profileHint': 'Liên kết User vào hồ sơ Employee.',
      'empty.schedule': 'Không có ca',
      'empty.scheduleHint': 'Ca đã phát hành sẽ xuất hiện tại đây.',
      'empty.sessions': 'Chưa có lượt chấm công',
      'empty.sessionsHint': 'Chấm công đầu tiên để bắt đầu.',
      'empty.entries': 'Chưa có dữ liệu công',
      'empty.entriesHint': 'Phát hành ca rồi mở lại kỳ.',
      'error.credential': 'Thông tin chấm công không hợp lệ.',
    },
    en: {
      'app.title': 'Attendance in admin',
      'app.summary': 'Kiosks, self-service, and attendance closing.',
      'app.category': 'Human Resources',
      'menu.app': 'Attendance',
      'menu.credentials': 'Kiosks and credentials',
      'menu.mine': 'My work',
      'my.title': 'My work',
      'my.profile': 'Profile',
      'my.schedule': 'Shift schedule',
      'my.sessions': 'Attendance history',
      'my.leave': 'Leave',
      'admin.title': 'Monthly attendance',
      'kiosk.title': 'Attendance kiosk',
      'kiosk.hint': 'Enter employee code and PIN, or scan a QR token.',
      'credentials.title': 'Kiosks and credentials',
      'credentials.kiosk': 'Issue kiosk',
      'credentials.pin': 'Set PIN',
      'credentials.qr': 'Reissue QR',
      'credentials.once': 'Secret shown once',
      'period.state': 'Period status',
      'period.reopenReason': 'Adjust a locked attendance period',
      'result.title': 'Result',
      'result.success': 'Success',
      'result.failed': 'Unable to complete',
      'punch.in': 'Checked in',
      'punch.out': 'Checked out',
      'field.employee': 'Employee',
      'field.employeeCode': 'Employee code',
      'field.branch': 'Branch',
      'field.date': 'Date',
      'field.start': 'Check in',
      'field.stop': 'Check out',
      'field.state': 'Status',
      'field.leaveType': 'Leave type',
      'field.dateFrom': 'From',
      'field.dateTo': 'To',
      'field.portion': 'Portion',
      'field.reason': 'Reason',
      'field.pin': 'PIN',
      'field.qr': 'QR token',
      'field.name': 'Name',
      'field.month': 'Month',
      'field.planned': 'Planned',
      'field.worked': 'Worked',
      'field.overtime': 'Approved overtime',
      'field.exception': 'Exception',
      'portion.full': 'Full day',
      'portion.morning': 'Morning',
      'portion.afternoon': 'Afternoon',
      'action.punch': 'Clock',
      'action.requestLeave': 'Request leave',
      'action.openPeriod': 'Open period',
      'action.close': 'Close period',
      'action.reopen': 'Reopen',
      'action.issue': 'Issue kiosk',
      'action.savePin': 'Save PIN',
      'action.issueQr': 'Issue QR',
      'state.open': 'Open',
      'state.closed': 'Closed',
      'state.locked': 'Locked',
      'empty.profile': 'No linked employee',
      'empty.profileHint': 'Link this User to an Employee record.',
      'empty.schedule': 'No shifts',
      'empty.scheduleHint': 'Published shifts appear here.',
      'empty.sessions': 'No attendance yet',
      'empty.sessionsHint': 'Clock in to begin.',
      'empty.entries': 'No attendance entries',
      'empty.entriesHint': 'Publish shifts and open the period again.',
      'error.credential': 'The attendance credential is invalid.',
    },
  },
})

export { credentialScreen, kioskScreen, myWorkScreen, periodScreen } from './screens.tsx'
